package quick

import (
	"context"
	"fmt"

	spotcontrol "github.com/mcMineyC/spotcontrol"
	"github.com/mcMineyC/spotcontrol/controller"
	"github.com/mcMineyC/spotcontrol/session"
)

// QuickConfig holds the configuration for the high-level Connect function.
// It provides sensible defaults for most fields so that the minimal usage is:
//
//	result, err := quick.Connect(ctx, quick.Config{
//	    StatePath:   "state.json",
//	    Interactive: true,
//	})
type QuickConfig struct {
	// StatePath is the file path for persisting session state (device ID,
	// credentials, OAuth2 tokens). If empty, no state is persisted and
	// DeviceId/Credentials must be provided via other means.
	StatePath string

	// DeviceName is the human-readable name shown in Spotify Connect device
	// lists. Defaults to "SpotControl".
	DeviceName string

	// DeviceType is the Spotify device type. Defaults to
	// spotcontrol.DeviceTypeComputer.
	DeviceType spotcontrol.DeviceType

	// DeviceId is the 40-hex-char device identifier. If empty and StatePath
	// is set, the ID is loaded from state or auto-generated. If both are
	// empty, a new ID is auto-generated by the session layer.
	DeviceId string

	// Interactive enables OAuth2 PKCE login when no stored credentials are
	// available. If false and no credentials exist, Connect returns an error.
	Interactive bool

	// CallbackPort is the local port for the OAuth2 callback server when
	// Interactive is true. 0 means a random available port.
	CallbackPort int

	// Log is the logger. If nil, spotcontrol.NewSimpleLogger(nil) is used.
	Log spotcontrol.Logger
}

// ConnectResult holds the session and controller returned by Connect.
type ConnectResult struct {
	Session    *session.Session
	Controller *controller.Controller
}

// Close shuts down both the controller and the session. It is safe to call
// Close multiple times.
func (r *ConnectResult) Close() {
	if r.Controller != nil {
		r.Controller.Close()
	}
	if r.Session != nil {
		r.Session.Close()
	}
}

// ---------------------------------------------------------------------------
// Pass-through methods for common controller commands
// ---------------------------------------------------------------------------

// Play resumes playback on the given device (or the active device if empty).
func (r *ConnectResult) Play(ctx context.Context, deviceId string) error {
	return r.Controller.Play(ctx, deviceId)
}

// Pause pauses playback on the given device (or the active device if empty).
func (r *ConnectResult) Pause(ctx context.Context, deviceId string) error {
	return r.Controller.Pause(ctx, deviceId)
}

// Next skips to the next track.
func (r *ConnectResult) Next(ctx context.Context, deviceId string) error {
	return r.Controller.Next(ctx, deviceId)
}

// Previous skips to the previous track.
func (r *ConnectResult) Previous(ctx context.Context, deviceId string) error {
	return r.Controller.Previous(ctx, deviceId)
}

// SetVolume sets the playback volume (0-100 percentage).
func (r *ConnectResult) SetVolume(ctx context.Context, volumePercent int, deviceId string) error {
	return r.Controller.SetVolume(ctx, volumePercent, deviceId)
}

// Seek seeks to the given position in the current track.
func (r *ConnectResult) Seek(ctx context.Context, positionMs int64, deviceId string) error {
	return r.Controller.Seek(ctx, positionMs, deviceId)
}

// SetShuffle enables or disables shuffle mode.
func (r *ConnectResult) SetShuffle(ctx context.Context, state bool, deviceId string) error {
	return r.Controller.SetShuffle(ctx, state, deviceId)
}

// SetRepeat sets the repeat mode ("off", "context", or "track").
func (r *ConnectResult) SetRepeat(ctx context.Context, state string, deviceId string) error {
	return r.Controller.SetRepeat(ctx, state, deviceId)
}

// LoadTrack starts playback of the given track URIs on the target device.
func (r *ConnectResult) LoadTrack(ctx context.Context, trackURIs []string, opts *controller.LoadTrackOptions) error {
	return r.Controller.LoadTrack(ctx, trackURIs, opts)
}

// ListDevices returns the list of devices from the cached connect-state cluster.
func (r *ConnectResult) ListDevices() []controller.DeviceInfo {
	return r.Controller.ListDevices()
}

// ListDevicesFromAPI queries the Spotify Web API for available devices.
func (r *ConnectResult) ListDevicesFromAPI(ctx context.Context) ([]controller.DeviceInfo, error) {
	return r.Controller.ListDevicesFromAPI(ctx)
}

// GetPlayerState returns the current playback state.
func (r *ConnectResult) GetPlayerState(ctx context.Context) (*controller.PlayerState, error) {
	return r.Controller.GetPlayerState(ctx)
}

// TransferPlayback transfers playback to the specified device.
func (r *ConnectResult) TransferPlayback(ctx context.Context, deviceId string, play bool) error {
	return r.Controller.TransferPlayback(ctx, deviceId, play)
}

// AddToQueue adds a track URI to the playback queue.
func (r *ConnectResult) AddToQueue(ctx context.Context, trackURI string, deviceId string) error {
	return r.Controller.AddToQueue(ctx, trackURI, deviceId)
}

// ---------------------------------------------------------------------------
// Connect — the high-level convenience constructor
// ---------------------------------------------------------------------------

// Connect is the high-level entry point for spotcontrol. It creates a session,
// builds a controller, starts the dealer connection, and optionally persists
// state — all in one call.
//
// The typical usage is:
//
//	result, err := quick.Connect(ctx, quick.QuickConfig{
//	    StatePath:   "spotcontrol_state.json",
//	    Interactive: true,
//	})
//	if err != nil { ... }
//	defer result.Close()
//	result.Play(ctx, "")
func Connect(ctx context.Context, cfg QuickConfig) (*ConnectResult, error) {
	// ---- Apply defaults ----
	cfg = ApplyDefaults(cfg)

	// ---- Load persisted state ----
	var state *spotcontrol.AppState
	if cfg.StatePath != "" {
		var err error
		state, err = spotcontrol.LoadState(cfg.StatePath)
		if err != nil {
			return nil, fmt.Errorf("spotcontrol: failed loading state from %s: %w", cfg.StatePath, err)
		}
	}

	// ---- Determine credentials ----
	var creds session.Credentials
	if state != nil && len(state.StoredCredentials) > 0 && state.Username != "" {
		cfg.Log.Infof("using stored credentials for user %s", spotcontrol.ObfuscateUsername(state.Username))
		creds = session.StoredCredentials{
			Username: state.Username,
			Data:     state.StoredCredentials,
		}
	} else if cfg.Interactive {
		creds = session.InteractiveCredentials{
			CallbackPort: cfg.CallbackPort,
		}
	} else {
		return nil, fmt.Errorf("spotcontrol: no credentials available (no stored state and Interactive is false)")
	}

	// ---- Determine device ID ----
	deviceId := cfg.DeviceId
	if deviceId == "" && state != nil && state.DeviceId != "" {
		deviceId = state.DeviceId
	}
	// If still empty, session.NewSessionFromOptions will auto-generate one.

	// ---- Create session ----
	sess, err := session.NewSessionFromOptions(ctx, &session.Options{
		Log:         cfg.Log,
		DeviceType:  cfg.DeviceType,
		DeviceId:    deviceId,
		DeviceName:  cfg.DeviceName,
		Credentials: creds,
		AppState:    state,
	})
	if err != nil {
		return nil, fmt.Errorf("spotcontrol: session creation failed: %w", err)
	}

	// ---- Create and start controller ----
	ctrl := sess.NewController()

	if err := ctrl.Start(ctx); err != nil {
		sess.Close()
		return nil, fmt.Errorf("spotcontrol: controller start failed: %w", err)
	}

	// ---- Persist state ----
	if cfg.StatePath != "" {
		if saveErr := spotcontrol.SaveState(cfg.StatePath, sess.ExportState()); saveErr != nil {
			cfg.Log.Warnf("failed saving state to %s: %v", cfg.StatePath, saveErr)
		} else {
			cfg.Log.Infof("saved session state to %s", cfg.StatePath)
		}
	}

	return &ConnectResult{
		Session:    sess,
		Controller: ctrl,
	}, nil
}

// ApplyDefaults fills in zero-valued fields in a QuickConfig with sensible
// defaults. This is exported so tests can verify defaulting logic without
// needing a live Spotify connection.
func ApplyDefaults(cfg QuickConfig) QuickConfig {
	if cfg.Log == nil {
		cfg.Log = spotcontrol.NewSimpleLogger(nil)
	}
	if cfg.DeviceName == "" {
		cfg.DeviceName = "SpotControl"
	}
	if cfg.DeviceType == 0 {
		cfg.DeviceType = spotcontrol.DeviceTypeComputer
	}
	return cfg
}
