// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spotify/clienttoken/data/v0/connectivity.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectivitySdkData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlatformSpecificData *PlatformSpecificData  `protobuf:"bytes,1,opt,name=platform_specific_data,json=platformSpecificData,proto3" json:"platform_specific_data,omitempty"`
	DeviceId             string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectivitySdkData) Reset() {
	*x = ConnectivitySdkData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectivitySdkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectivitySdkData) ProtoMessage() {}

func (x *ConnectivitySdkData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectivitySdkData.ProtoReflect.Descriptor instead.
func (*ConnectivitySdkData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectivitySdkData) GetPlatformSpecificData() *PlatformSpecificData {
	if x != nil {
		return x.PlatformSpecificData
	}
	return nil
}

func (x *ConnectivitySdkData) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type PlatformSpecificData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*PlatformSpecificData_Android
	//	*PlatformSpecificData_Ios
	//	*PlatformSpecificData_DesktopWindows
	//	*PlatformSpecificData_DesktopLinux
	//	*PlatformSpecificData_DesktopMacos
	Data          isPlatformSpecificData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformSpecificData) Reset() {
	*x = PlatformSpecificData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSpecificData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSpecificData) ProtoMessage() {}

func (x *PlatformSpecificData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformSpecificData.ProtoReflect.Descriptor instead.
func (*PlatformSpecificData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformSpecificData) GetData() isPlatformSpecificData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PlatformSpecificData) GetAndroid() *NativeAndroidData {
	if x != nil {
		if x, ok := x.Data.(*PlatformSpecificData_Android); ok {
			return x.Android
		}
	}
	return nil
}

func (x *PlatformSpecificData) GetIos() *NativeIOSData {
	if x != nil {
		if x, ok := x.Data.(*PlatformSpecificData_Ios); ok {
			return x.Ios
		}
	}
	return nil
}

func (x *PlatformSpecificData) GetDesktopWindows() *NativeDesktopWindowsData {
	if x != nil {
		if x, ok := x.Data.(*PlatformSpecificData_DesktopWindows); ok {
			return x.DesktopWindows
		}
	}
	return nil
}

func (x *PlatformSpecificData) GetDesktopLinux() *NativeDesktopLinuxData {
	if x != nil {
		if x, ok := x.Data.(*PlatformSpecificData_DesktopLinux); ok {
			return x.DesktopLinux
		}
	}
	return nil
}

func (x *PlatformSpecificData) GetDesktopMacos() *NativeDesktopMacOSData {
	if x != nil {
		if x, ok := x.Data.(*PlatformSpecificData_DesktopMacos); ok {
			return x.DesktopMacos
		}
	}
	return nil
}

type isPlatformSpecificData_Data interface {
	isPlatformSpecificData_Data()
}

type PlatformSpecificData_Android struct {
	Android *NativeAndroidData `protobuf:"bytes,1,opt,name=android,proto3,oneof"`
}

type PlatformSpecificData_Ios struct {
	Ios *NativeIOSData `protobuf:"bytes,2,opt,name=ios,proto3,oneof"`
}

type PlatformSpecificData_DesktopWindows struct {
	DesktopWindows *NativeDesktopWindowsData `protobuf:"bytes,3,opt,name=desktop_windows,json=desktopWindows,proto3,oneof"`
}

type PlatformSpecificData_DesktopLinux struct {
	DesktopLinux *NativeDesktopLinuxData `protobuf:"bytes,4,opt,name=desktop_linux,json=desktopLinux,proto3,oneof"`
}

type PlatformSpecificData_DesktopMacos struct {
	DesktopMacos *NativeDesktopMacOSData `protobuf:"bytes,5,opt,name=desktop_macos,json=desktopMacos,proto3,oneof"`
}

func (*PlatformSpecificData_Android) isPlatformSpecificData_Data() {}

func (*PlatformSpecificData_Ios) isPlatformSpecificData_Data() {}

func (*PlatformSpecificData_DesktopWindows) isPlatformSpecificData_Data() {}

func (*PlatformSpecificData_DesktopLinux) isPlatformSpecificData_Data() {}

func (*PlatformSpecificData_DesktopMacos) isPlatformSpecificData_Data() {}

type NativeAndroidData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MajorVersion       int32                  `protobuf:"varint,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion       int32                  `protobuf:"varint,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	PatchVersion       int32                  `protobuf:"varint,3,opt,name=patch_version,json=patchVersion,proto3" json:"patch_version,omitempty"`
	ApiVersion         int32                  `protobuf:"varint,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	DeviceName         string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceManufacturer string                 `protobuf:"bytes,6,opt,name=device_manufacturer,json=deviceManufacturer,proto3" json:"device_manufacturer,omitempty"`
	DeviceBrand        string                 `protobuf:"bytes,7,opt,name=device_brand,json=deviceBrand,proto3" json:"device_brand,omitempty"`
	DeviceModel        string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	DeviceArch         string                 `protobuf:"bytes,9,opt,name=device_arch,json=deviceArch,proto3" json:"device_arch,omitempty"`
	ScreenDimensions   *ScreenDimensions      `protobuf:"bytes,10,opt,name=screen_dimensions,json=screenDimensions,proto3" json:"screen_dimensions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NativeAndroidData) Reset() {
	*x = NativeAndroidData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeAndroidData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeAndroidData) ProtoMessage() {}

func (x *NativeAndroidData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeAndroidData.ProtoReflect.Descriptor instead.
func (*NativeAndroidData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{2}
}

func (x *NativeAndroidData) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *NativeAndroidData) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *NativeAndroidData) GetPatchVersion() int32 {
	if x != nil {
		return x.PatchVersion
	}
	return 0
}

func (x *NativeAndroidData) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *NativeAndroidData) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *NativeAndroidData) GetDeviceManufacturer() string {
	if x != nil {
		return x.DeviceManufacturer
	}
	return ""
}

func (x *NativeAndroidData) GetDeviceBrand() string {
	if x != nil {
		return x.DeviceBrand
	}
	return ""
}

func (x *NativeAndroidData) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *NativeAndroidData) GetDeviceArch() string {
	if x != nil {
		return x.DeviceArch
	}
	return ""
}

func (x *NativeAndroidData) GetScreenDimensions() *ScreenDimensions {
	if x != nil {
		return x.ScreenDimensions
	}
	return nil
}

type NativeIOSData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MajorVersion          int32                  `protobuf:"varint,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion          int32                  `protobuf:"varint,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	PatchVersion          int32                  `protobuf:"varint,3,opt,name=patch_version,json=patchVersion,proto3" json:"patch_version,omitempty"`
	UserInterfaceIdiom    string                 `protobuf:"bytes,4,opt,name=user_interface_idiom,json=userInterfaceIdiom,proto3" json:"user_interface_idiom,omitempty"`
	TargetIphoneSimulator bool                   `protobuf:"varint,5,opt,name=target_iphone_simulator,json=targetIphoneSimulator,proto3" json:"target_iphone_simulator,omitempty"`
	HwMachine             string                 `protobuf:"bytes,6,opt,name=hw_machine,json=hwMachine,proto3" json:"hw_machine,omitempty"`
	ScreenDimensions      *ScreenDimensions      `protobuf:"bytes,7,opt,name=screen_dimensions,json=screenDimensions,proto3" json:"screen_dimensions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NativeIOSData) Reset() {
	*x = NativeIOSData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeIOSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeIOSData) ProtoMessage() {}

func (x *NativeIOSData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeIOSData.ProtoReflect.Descriptor instead.
func (*NativeIOSData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{3}
}

func (x *NativeIOSData) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *NativeIOSData) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *NativeIOSData) GetPatchVersion() int32 {
	if x != nil {
		return x.PatchVersion
	}
	return 0
}

func (x *NativeIOSData) GetUserInterfaceIdiom() string {
	if x != nil {
		return x.UserInterfaceIdiom
	}
	return ""
}

func (x *NativeIOSData) GetTargetIphoneSimulator() bool {
	if x != nil {
		return x.TargetIphoneSimulator
	}
	return false
}

func (x *NativeIOSData) GetHwMachine() string {
	if x != nil {
		return x.HwMachine
	}
	return ""
}

func (x *NativeIOSData) GetScreenDimensions() *ScreenDimensions {
	if x != nil {
		return x.ScreenDimensions
	}
	return nil
}

type NativeDesktopWindowsData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OsVersion        int32                  `protobuf:"varint,1,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsBuild          int32                  `protobuf:"varint,3,opt,name=os_build,json=osBuild,proto3" json:"os_build,omitempty"`
	PlatformId       bool                   `protobuf:"varint,4,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Unknown          bool                   `protobuf:"varint,5,opt,name=unknown,proto3" json:"unknown,omitempty"`
	ImageFileMachine string                 `protobuf:"bytes,6,opt,name=image_file_machine,json=imageFileMachine,proto3" json:"image_file_machine,omitempty"`
	PeKind           bool                   `protobuf:"varint,7,opt,name=pe_kind,json=peKind,proto3" json:"pe_kind,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NativeDesktopWindowsData) Reset() {
	*x = NativeDesktopWindowsData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeDesktopWindowsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeDesktopWindowsData) ProtoMessage() {}

func (x *NativeDesktopWindowsData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeDesktopWindowsData.ProtoReflect.Descriptor instead.
func (*NativeDesktopWindowsData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{4}
}

func (x *NativeDesktopWindowsData) GetOsVersion() int32 {
	if x != nil {
		return x.OsVersion
	}
	return 0
}

func (x *NativeDesktopWindowsData) GetOsBuild() int32 {
	if x != nil {
		return x.OsBuild
	}
	return 0
}

func (x *NativeDesktopWindowsData) GetPlatformId() bool {
	if x != nil {
		return x.PlatformId
	}
	return false
}

func (x *NativeDesktopWindowsData) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

func (x *NativeDesktopWindowsData) GetImageFileMachine() string {
	if x != nil {
		return x.ImageFileMachine
	}
	return ""
}

func (x *NativeDesktopWindowsData) GetPeKind() bool {
	if x != nil {
		return x.PeKind
	}
	return false
}

type NativeDesktopLinuxData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemName    string                 `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	SystemRelease string                 `protobuf:"bytes,2,opt,name=system_release,json=systemRelease,proto3" json:"system_release,omitempty"`
	SystemVersion string                 `protobuf:"bytes,3,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	Hardware      string                 `protobuf:"bytes,4,opt,name=hardware,proto3" json:"hardware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeDesktopLinuxData) Reset() {
	*x = NativeDesktopLinuxData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeDesktopLinuxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeDesktopLinuxData) ProtoMessage() {}

func (x *NativeDesktopLinuxData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeDesktopLinuxData.ProtoReflect.Descriptor instead.
func (*NativeDesktopLinuxData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{5}
}

func (x *NativeDesktopLinuxData) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *NativeDesktopLinuxData) GetSystemRelease() string {
	if x != nil {
		return x.SystemRelease
	}
	return ""
}

func (x *NativeDesktopLinuxData) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *NativeDesktopLinuxData) GetHardware() string {
	if x != nil {
		return x.Hardware
	}
	return ""
}

type NativeDesktopMacOSData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SystemVersion   string                 `protobuf:"bytes,1,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	HwModel         string                 `protobuf:"bytes,2,opt,name=hw_model,json=hwModel,proto3" json:"hw_model,omitempty"`
	CompiledCpuType string                 `protobuf:"bytes,3,opt,name=compiled_cpu_type,json=compiledCpuType,proto3" json:"compiled_cpu_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NativeDesktopMacOSData) Reset() {
	*x = NativeDesktopMacOSData{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeDesktopMacOSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeDesktopMacOSData) ProtoMessage() {}

func (x *NativeDesktopMacOSData) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeDesktopMacOSData.ProtoReflect.Descriptor instead.
func (*NativeDesktopMacOSData) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{6}
}

func (x *NativeDesktopMacOSData) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *NativeDesktopMacOSData) GetHwModel() string {
	if x != nil {
		return x.HwModel
	}
	return ""
}

func (x *NativeDesktopMacOSData) GetCompiledCpuType() string {
	if x != nil {
		return x.CompiledCpuType
	}
	return ""
}

type ScreenDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Density       int32                  `protobuf:"varint,3,opt,name=density,proto3" json:"density,omitempty"`
	UnknownValue  int32                  `protobuf:"varint,4,opt,name=unknown_value,json=unknownValue,proto3" json:"unknown_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDimensions) Reset() {
	*x = ScreenDimensions{}
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDimensions) ProtoMessage() {}

func (x *ScreenDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDimensions.ProtoReflect.Descriptor instead.
func (*ScreenDimensions) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP(), []int{7}
}

func (x *ScreenDimensions) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenDimensions) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenDimensions) GetDensity() int32 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *ScreenDimensions) GetUnknownValue() int32 {
	if x != nil {
		return x.UnknownValue
	}
	return 0
}

var File_spotify_clienttoken_data_v0_connectivity_proto protoreflect.FileDescriptor

const file_spotify_clienttoken_data_v0_connectivity_proto_rawDesc = "" +
	"\n" +
	".spotify/clienttoken/data/v0/connectivity.proto\x12\x1bspotify.clienttoken.data.v0\"\x9b\x01\n" +
	"\x13ConnectivitySdkData\x12g\n" +
	"\x16platform_specific_data\x18\x01 \x01(\v21.spotify.clienttoken.data.v0.PlatformSpecificDataR\x14platformSpecificData\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\xc4\x03\n" +
	"\x14PlatformSpecificData\x12J\n" +
	"\aandroid\x18\x01 \x01(\v2..spotify.clienttoken.data.v0.NativeAndroidDataH\x00R\aandroid\x12>\n" +
	"\x03ios\x18\x02 \x01(\v2*.spotify.clienttoken.data.v0.NativeIOSDataH\x00R\x03ios\x12`\n" +
	"\x0fdesktop_windows\x18\x03 \x01(\v25.spotify.clienttoken.data.v0.NativeDesktopWindowsDataH\x00R\x0edesktopWindows\x12Z\n" +
	"\rdesktop_linux\x18\x04 \x01(\v23.spotify.clienttoken.data.v0.NativeDesktopLinuxDataH\x00R\fdesktopLinux\x12Z\n" +
	"\rdesktop_macos\x18\x05 \x01(\v23.spotify.clienttoken.data.v0.NativeDesktopMacOSDataH\x00R\fdesktopMacosB\x06\n" +
	"\x04data\"\xb8\x03\n" +
	"\x11NativeAndroidData\x12#\n" +
	"\rmajor_version\x18\x01 \x01(\x05R\fmajorVersion\x12#\n" +
	"\rminor_version\x18\x02 \x01(\x05R\fminorVersion\x12#\n" +
	"\rpatch_version\x18\x03 \x01(\x05R\fpatchVersion\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\x05R\n" +
	"apiVersion\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12/\n" +
	"\x13device_manufacturer\x18\x06 \x01(\tR\x12deviceManufacturer\x12!\n" +
	"\fdevice_brand\x18\a \x01(\tR\vdeviceBrand\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12\x1f\n" +
	"\vdevice_arch\x18\t \x01(\tR\n" +
	"deviceArch\x12Z\n" +
	"\x11screen_dimensions\x18\n" +
	" \x01(\v2-.spotify.clienttoken.data.v0.ScreenDimensionsR\x10screenDimensions\"\xe3\x02\n" +
	"\rNativeIOSData\x12#\n" +
	"\rmajor_version\x18\x01 \x01(\x05R\fmajorVersion\x12#\n" +
	"\rminor_version\x18\x02 \x01(\x05R\fminorVersion\x12#\n" +
	"\rpatch_version\x18\x03 \x01(\x05R\fpatchVersion\x120\n" +
	"\x14user_interface_idiom\x18\x04 \x01(\tR\x12userInterfaceIdiom\x126\n" +
	"\x17target_iphone_simulator\x18\x05 \x01(\bR\x15targetIphoneSimulator\x12\x1d\n" +
	"\n" +
	"hw_machine\x18\x06 \x01(\tR\thwMachine\x12Z\n" +
	"\x11screen_dimensions\x18\a \x01(\v2-.spotify.clienttoken.data.v0.ScreenDimensionsR\x10screenDimensions\"\xd6\x01\n" +
	"\x18NativeDesktopWindowsData\x12\x1d\n" +
	"\n" +
	"os_version\x18\x01 \x01(\x05R\tosVersion\x12\x19\n" +
	"\bos_build\x18\x03 \x01(\x05R\aosBuild\x12\x1f\n" +
	"\vplatform_id\x18\x04 \x01(\bR\n" +
	"platformId\x12\x18\n" +
	"\aunknown\x18\x05 \x01(\bR\aunknown\x12,\n" +
	"\x12image_file_machine\x18\x06 \x01(\tR\x10imageFileMachine\x12\x17\n" +
	"\ape_kind\x18\a \x01(\bR\x06peKind\"\xa3\x01\n" +
	"\x16NativeDesktopLinuxData\x12\x1f\n" +
	"\vsystem_name\x18\x01 \x01(\tR\n" +
	"systemName\x12%\n" +
	"\x0esystem_release\x18\x02 \x01(\tR\rsystemRelease\x12%\n" +
	"\x0esystem_version\x18\x03 \x01(\tR\rsystemVersion\x12\x1a\n" +
	"\bhardware\x18\x04 \x01(\tR\bhardware\"\x86\x01\n" +
	"\x16NativeDesktopMacOSData\x12%\n" +
	"\x0esystem_version\x18\x01 \x01(\tR\rsystemVersion\x12\x19\n" +
	"\bhw_model\x18\x02 \x01(\tR\ahwModel\x12*\n" +
	"\x11compiled_cpu_type\x18\x03 \x01(\tR\x0fcompiledCpuType\"\x7f\n" +
	"\x10ScreenDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x18\n" +
	"\adensity\x18\x03 \x01(\x05R\adensity\x12#\n" +
	"\runknown_value\x18\x04 \x01(\x05R\funknownValueBGZEgithub.com/badfortrains/spotcontrol/proto/spotify/clienttoken/data/v0b\x06proto3"

var (
	file_spotify_clienttoken_data_v0_connectivity_proto_rawDescOnce sync.Once
	file_spotify_clienttoken_data_v0_connectivity_proto_rawDescData []byte
)

func file_spotify_clienttoken_data_v0_connectivity_proto_rawDescGZIP() []byte {
	file_spotify_clienttoken_data_v0_connectivity_proto_rawDescOnce.Do(func() {
		file_spotify_clienttoken_data_v0_connectivity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_clienttoken_data_v0_connectivity_proto_rawDesc), len(file_spotify_clienttoken_data_v0_connectivity_proto_rawDesc)))
	})
	return file_spotify_clienttoken_data_v0_connectivity_proto_rawDescData
}

var file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spotify_clienttoken_data_v0_connectivity_proto_goTypes = []any{
	(*ConnectivitySdkData)(nil),      // 0: spotify.clienttoken.data.v0.ConnectivitySdkData
	(*PlatformSpecificData)(nil),     // 1: spotify.clienttoken.data.v0.PlatformSpecificData
	(*NativeAndroidData)(nil),        // 2: spotify.clienttoken.data.v0.NativeAndroidData
	(*NativeIOSData)(nil),            // 3: spotify.clienttoken.data.v0.NativeIOSData
	(*NativeDesktopWindowsData)(nil), // 4: spotify.clienttoken.data.v0.NativeDesktopWindowsData
	(*NativeDesktopLinuxData)(nil),   // 5: spotify.clienttoken.data.v0.NativeDesktopLinuxData
	(*NativeDesktopMacOSData)(nil),   // 6: spotify.clienttoken.data.v0.NativeDesktopMacOSData
	(*ScreenDimensions)(nil),         // 7: spotify.clienttoken.data.v0.ScreenDimensions
}
var file_spotify_clienttoken_data_v0_connectivity_proto_depIdxs = []int32{
	1, // 0: spotify.clienttoken.data.v0.ConnectivitySdkData.platform_specific_data:type_name -> spotify.clienttoken.data.v0.PlatformSpecificData
	2, // 1: spotify.clienttoken.data.v0.PlatformSpecificData.android:type_name -> spotify.clienttoken.data.v0.NativeAndroidData
	3, // 2: spotify.clienttoken.data.v0.PlatformSpecificData.ios:type_name -> spotify.clienttoken.data.v0.NativeIOSData
	4, // 3: spotify.clienttoken.data.v0.PlatformSpecificData.desktop_windows:type_name -> spotify.clienttoken.data.v0.NativeDesktopWindowsData
	5, // 4: spotify.clienttoken.data.v0.PlatformSpecificData.desktop_linux:type_name -> spotify.clienttoken.data.v0.NativeDesktopLinuxData
	6, // 5: spotify.clienttoken.data.v0.PlatformSpecificData.desktop_macos:type_name -> spotify.clienttoken.data.v0.NativeDesktopMacOSData
	7, // 6: spotify.clienttoken.data.v0.NativeAndroidData.screen_dimensions:type_name -> spotify.clienttoken.data.v0.ScreenDimensions
	7, // 7: spotify.clienttoken.data.v0.NativeIOSData.screen_dimensions:type_name -> spotify.clienttoken.data.v0.ScreenDimensions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_spotify_clienttoken_data_v0_connectivity_proto_init() }
func file_spotify_clienttoken_data_v0_connectivity_proto_init() {
	if File_spotify_clienttoken_data_v0_connectivity_proto != nil {
		return
	}
	file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes[1].OneofWrappers = []any{
		(*PlatformSpecificData_Android)(nil),
		(*PlatformSpecificData_Ios)(nil),
		(*PlatformSpecificData_DesktopWindows)(nil),
		(*PlatformSpecificData_DesktopLinux)(nil),
		(*PlatformSpecificData_DesktopMacos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_clienttoken_data_v0_connectivity_proto_rawDesc), len(file_spotify_clienttoken_data_v0_connectivity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_clienttoken_data_v0_connectivity_proto_goTypes,
		DependencyIndexes: file_spotify_clienttoken_data_v0_connectivity_proto_depIdxs,
		MessageInfos:      file_spotify_clienttoken_data_v0_connectivity_proto_msgTypes,
	}.Build()
	File_spotify_clienttoken_data_v0_connectivity_proto = out.File
	file_spotify_clienttoken_data_v0_connectivity_proto_goTypes = nil
	file_spotify_clienttoken_data_v0_connectivity_proto_depIdxs = nil
}
