// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/policy/supported_link_types_in_playlists.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkType int32

const (
	LinkType_EMPTY       LinkType = 0
	LinkType_ARTIST      LinkType = 1
	LinkType_ALBUM       LinkType = 2
	LinkType_TRACK       LinkType = 4
	LinkType_LOCAL_TRACK LinkType = 9
	LinkType_SHOW        LinkType = 62
	LinkType_EPISODE     LinkType = 63
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0:  "EMPTY",
		1:  "ARTIST",
		2:  "ALBUM",
		4:  "TRACK",
		9:  "LOCAL_TRACK",
		62: "SHOW",
		63: "EPISODE",
	}
	LinkType_value = map[string]int32{
		"EMPTY":       0,
		"ARTIST":      1,
		"ALBUM":       2,
		"TRACK":       4,
		"LOCAL_TRACK": 9,
		"SHOW":        62,
		"EPISODE":     63,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_policy_supported_link_types_in_playlists_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_spotify_policy_supported_link_types_in_playlists_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_policy_supported_link_types_in_playlists_proto_rawDescGZIP(), []int{0}
}

var File_spotify_policy_supported_link_types_in_playlists_proto protoreflect.FileDescriptor

const file_spotify_policy_supported_link_types_in_playlists_proto_rawDesc = "" +
	"\n" +
	"6spotify/policy/supported_link_types_in_playlists.proto\x12\x1dspotify.playlist.cosmos.proto*_\n" +
	"\bLinkType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\n" +
	"\n" +
	"\x06ARTIST\x10\x01\x12\t\n" +
	"\x05ALBUM\x10\x02\x12\t\n" +
	"\x05TRACK\x10\x04\x12\x0f\n" +
	"\vLOCAL_TRACK\x10\t\x12\b\n" +
	"\x04SHOW\x10>\x12\v\n" +
	"\aEPISODE\x10?B\x97\x02\n" +
	"!com.spotify.playlist.cosmos.protoB\"SupportedLinkTypesInPlaylistsProtoP\x01Z6github.com/mcMineyC/spotcontrol/proto/spotify/policy\xa2\x02\x04SPCP\xaa\x02\x1dSpotify.Playlist.Cosmos.Proto\xca\x02\x1dSpotify\\Playlist\\Cosmos\\Proto\xe2\x02)Spotify\\Playlist\\Cosmos\\Proto\\GPBMetadata\xea\x02 Spotify::Playlist::Cosmos::Protob\x06proto3"

var (
	file_spotify_policy_supported_link_types_in_playlists_proto_rawDescOnce sync.Once
	file_spotify_policy_supported_link_types_in_playlists_proto_rawDescData []byte
)

func file_spotify_policy_supported_link_types_in_playlists_proto_rawDescGZIP() []byte {
	file_spotify_policy_supported_link_types_in_playlists_proto_rawDescOnce.Do(func() {
		file_spotify_policy_supported_link_types_in_playlists_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_policy_supported_link_types_in_playlists_proto_rawDesc), len(file_spotify_policy_supported_link_types_in_playlists_proto_rawDesc)))
	})
	return file_spotify_policy_supported_link_types_in_playlists_proto_rawDescData
}

var file_spotify_policy_supported_link_types_in_playlists_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spotify_policy_supported_link_types_in_playlists_proto_goTypes = []any{
	(LinkType)(0), // 0: spotify.playlist.cosmos.proto.LinkType
}
var file_spotify_policy_supported_link_types_in_playlists_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spotify_policy_supported_link_types_in_playlists_proto_init() }
func file_spotify_policy_supported_link_types_in_playlists_proto_init() {
	if File_spotify_policy_supported_link_types_in_playlists_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_policy_supported_link_types_in_playlists_proto_rawDesc), len(file_spotify_policy_supported_link_types_in_playlists_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_policy_supported_link_types_in_playlists_proto_goTypes,
		DependencyIndexes: file_spotify_policy_supported_link_types_in_playlists_proto_depIdxs,
		EnumInfos:         file_spotify_policy_supported_link_types_in_playlists_proto_enumTypes,
	}.Build()
	File_spotify_policy_supported_link_types_in_playlists_proto = out.File
	file_spotify_policy_supported_link_types_in_playlists_proto_goTypes = nil
	file_spotify_policy_supported_link_types_in_playlists_proto_depIdxs = nil
}
