// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spotify/clienttoken/http/v0/clienttoken.proto

package v0

import (
	v0 "github.com/mcMineyC/spotcontrol/proto/spotify/clienttoken/data/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientTokenRequestType int32

const (
	ClientTokenRequestType_REQUEST_UNKNOWN                   ClientTokenRequestType = 0
	ClientTokenRequestType_REQUEST_CLIENT_DATA_REQUEST       ClientTokenRequestType = 1
	ClientTokenRequestType_REQUEST_CHALLENGE_ANSWERS_REQUEST ClientTokenRequestType = 2
)

// Enum value maps for ClientTokenRequestType.
var (
	ClientTokenRequestType_name = map[int32]string{
		0: "REQUEST_UNKNOWN",
		1: "REQUEST_CLIENT_DATA_REQUEST",
		2: "REQUEST_CHALLENGE_ANSWERS_REQUEST",
	}
	ClientTokenRequestType_value = map[string]int32{
		"REQUEST_UNKNOWN":                   0,
		"REQUEST_CLIENT_DATA_REQUEST":       1,
		"REQUEST_CHALLENGE_ANSWERS_REQUEST": 2,
	}
)

func (x ClientTokenRequestType) Enum() *ClientTokenRequestType {
	p := new(ClientTokenRequestType)
	*p = x
	return p
}

func (x ClientTokenRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTokenRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[0].Descriptor()
}

func (ClientTokenRequestType) Type() protoreflect.EnumType {
	return &file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[0]
}

func (x ClientTokenRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTokenRequestType.Descriptor instead.
func (ClientTokenRequestType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{0}
}

type ClientTokenResponseType int32

const (
	ClientTokenResponseType_RESPONSE_UNKNOWN                ClientTokenResponseType = 0
	ClientTokenResponseType_RESPONSE_GRANTED_TOKEN_RESPONSE ClientTokenResponseType = 1
	ClientTokenResponseType_RESPONSE_CHALLENGES_RESPONSE    ClientTokenResponseType = 2
)

// Enum value maps for ClientTokenResponseType.
var (
	ClientTokenResponseType_name = map[int32]string{
		0: "RESPONSE_UNKNOWN",
		1: "RESPONSE_GRANTED_TOKEN_RESPONSE",
		2: "RESPONSE_CHALLENGES_RESPONSE",
	}
	ClientTokenResponseType_value = map[string]int32{
		"RESPONSE_UNKNOWN":                0,
		"RESPONSE_GRANTED_TOKEN_RESPONSE": 1,
		"RESPONSE_CHALLENGES_RESPONSE":    2,
	}
)

func (x ClientTokenResponseType) Enum() *ClientTokenResponseType {
	p := new(ClientTokenResponseType)
	*p = x
	return p
}

func (x ClientTokenResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTokenResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[1].Descriptor()
}

func (ClientTokenResponseType) Type() protoreflect.EnumType {
	return &file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[1]
}

func (x ClientTokenResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTokenResponseType.Descriptor instead.
func (ClientTokenResponseType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{1}
}

type ClientTokenRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RequestType ClientTokenRequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=spotify.clienttoken.http.v0.ClientTokenRequestType" json:"request_type,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*ClientTokenRequest_ClientData
	//	*ClientTokenRequest_ChallengeAnswers
	Request       isClientTokenRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTokenRequest) Reset() {
	*x = ClientTokenRequest{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTokenRequest) ProtoMessage() {}

func (x *ClientTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTokenRequest.ProtoReflect.Descriptor instead.
func (*ClientTokenRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{0}
}

func (x *ClientTokenRequest) GetRequestType() ClientTokenRequestType {
	if x != nil {
		return x.RequestType
	}
	return ClientTokenRequestType_REQUEST_UNKNOWN
}

func (x *ClientTokenRequest) GetRequest() isClientTokenRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClientTokenRequest) GetClientData() *ClientDataRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientTokenRequest_ClientData); ok {
			return x.ClientData
		}
	}
	return nil
}

func (x *ClientTokenRequest) GetChallengeAnswers() *ChallengeAnswersRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientTokenRequest_ChallengeAnswers); ok {
			return x.ChallengeAnswers
		}
	}
	return nil
}

type isClientTokenRequest_Request interface {
	isClientTokenRequest_Request()
}

type ClientTokenRequest_ClientData struct {
	ClientData *ClientDataRequest `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3,oneof"`
}

type ClientTokenRequest_ChallengeAnswers struct {
	ChallengeAnswers *ChallengeAnswersRequest `protobuf:"bytes,3,opt,name=challenge_answers,json=challengeAnswers,proto3,oneof"`
}

func (*ClientTokenRequest_ClientData) isClientTokenRequest_Request() {}

func (*ClientTokenRequest_ChallengeAnswers) isClientTokenRequest_Request() {}

type ClientDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientDataRequest_ConnectivitySdkData
	Data          isClientDataRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDataRequest) Reset() {
	*x = ClientDataRequest{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataRequest) ProtoMessage() {}

func (x *ClientDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataRequest.ProtoReflect.Descriptor instead.
func (*ClientDataRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDataRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientDataRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDataRequest) GetData() isClientDataRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientDataRequest) GetConnectivitySdkData() *v0.ConnectivitySdkData {
	if x != nil {
		if x, ok := x.Data.(*ClientDataRequest_ConnectivitySdkData); ok {
			return x.ConnectivitySdkData
		}
	}
	return nil
}

type isClientDataRequest_Data interface {
	isClientDataRequest_Data()
}

type ClientDataRequest_ConnectivitySdkData struct {
	ConnectivitySdkData *v0.ConnectivitySdkData `protobuf:"bytes,3,opt,name=connectivity_sdk_data,json=connectivitySdkData,proto3,oneof"`
}

func (*ClientDataRequest_ConnectivitySdkData) isClientDataRequest_Data() {}

type ChallengeAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Answers       []*ChallengeAnswer     `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeAnswersRequest) Reset() {
	*x = ChallengeAnswersRequest{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeAnswersRequest) ProtoMessage() {}

func (x *ChallengeAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeAnswersRequest.ProtoReflect.Descriptor instead.
func (*ChallengeAnswersRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeAnswersRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChallengeAnswersRequest) GetAnswers() []*ChallengeAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type ChallengeAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Answer:
	//
	//	*ChallengeAnswer_HashCash
	//	*ChallengeAnswer_Code
	//	*ChallengeAnswer_EvaluateJs
	Answer        isChallengeAnswer_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeAnswer) Reset() {
	*x = ChallengeAnswer{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeAnswer) ProtoMessage() {}

func (x *ChallengeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeAnswer.ProtoReflect.Descriptor instead.
func (*ChallengeAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{3}
}

func (x *ChallengeAnswer) GetAnswer() isChallengeAnswer_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *ChallengeAnswer) GetHashCash() *HashCashAnswer {
	if x != nil {
		if x, ok := x.Answer.(*ChallengeAnswer_HashCash); ok {
			return x.HashCash
		}
	}
	return nil
}

func (x *ChallengeAnswer) GetCode() *CodeAnswer {
	if x != nil {
		if x, ok := x.Answer.(*ChallengeAnswer_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *ChallengeAnswer) GetEvaluateJs() *EvaluateJSAnswer {
	if x != nil {
		if x, ok := x.Answer.(*ChallengeAnswer_EvaluateJs); ok {
			return x.EvaluateJs
		}
	}
	return nil
}

type isChallengeAnswer_Answer interface {
	isChallengeAnswer_Answer()
}

type ChallengeAnswer_HashCash struct {
	HashCash *HashCashAnswer `protobuf:"bytes,1,opt,name=hash_cash,json=hashCash,proto3,oneof"`
}

type ChallengeAnswer_Code struct {
	Code *CodeAnswer `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type ChallengeAnswer_EvaluateJs struct {
	EvaluateJs *EvaluateJSAnswer `protobuf:"bytes,3,opt,name=evaluate_js,json=evaluateJs,proto3,oneof"`
}

func (*ChallengeAnswer_HashCash) isChallengeAnswer_Answer() {}

func (*ChallengeAnswer_Code) isChallengeAnswer_Answer() {}

func (*ChallengeAnswer_EvaluateJs) isChallengeAnswer_Answer() {}

type HashCashAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suffix        []byte                 `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashCashAnswer) Reset() {
	*x = HashCashAnswer{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashCashAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashCashAnswer) ProtoMessage() {}

func (x *HashCashAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashCashAnswer.ProtoReflect.Descriptor instead.
func (*HashCashAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{4}
}

func (x *HashCashAnswer) GetSuffix() []byte {
	if x != nil {
		return x.Suffix
	}
	return nil
}

func (x *HashCashAnswer) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CodeAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeAnswer) Reset() {
	*x = CodeAnswer{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAnswer) ProtoMessage() {}

func (x *CodeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAnswer.ProtoReflect.Descriptor instead.
func (*CodeAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{5}
}

func (x *CodeAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EvaluateJSAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateJSAnswer) Reset() {
	*x = EvaluateJSAnswer{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateJSAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateJSAnswer) ProtoMessage() {}

func (x *EvaluateJSAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateJSAnswer.ProtoReflect.Descriptor instead.
func (*EvaluateJSAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateJSAnswer) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ClientTokenResponse struct {
	state        protoimpl.MessageState  `protogen:"open.v1"`
	ResponseType ClientTokenResponseType `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=spotify.clienttoken.http.v0.ClientTokenResponseType" json:"response_type,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientTokenResponse_GrantedToken
	//	*ClientTokenResponse_Challenges
	Response      isClientTokenResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTokenResponse) Reset() {
	*x = ClientTokenResponse{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTokenResponse) ProtoMessage() {}

func (x *ClientTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTokenResponse.ProtoReflect.Descriptor instead.
func (*ClientTokenResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{7}
}

func (x *ClientTokenResponse) GetResponseType() ClientTokenResponseType {
	if x != nil {
		return x.ResponseType
	}
	return ClientTokenResponseType_RESPONSE_UNKNOWN
}

func (x *ClientTokenResponse) GetResponse() isClientTokenResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientTokenResponse) GetGrantedToken() *GrantedTokenResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientTokenResponse_GrantedToken); ok {
			return x.GrantedToken
		}
	}
	return nil
}

func (x *ClientTokenResponse) GetChallenges() *ChallengesResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientTokenResponse_Challenges); ok {
			return x.Challenges
		}
	}
	return nil
}

type isClientTokenResponse_Response interface {
	isClientTokenResponse_Response()
}

type ClientTokenResponse_GrantedToken struct {
	GrantedToken *GrantedTokenResponse `protobuf:"bytes,2,opt,name=granted_token,json=grantedToken,proto3,oneof"`
}

type ClientTokenResponse_Challenges struct {
	Challenges *ChallengesResponse `protobuf:"bytes,3,opt,name=challenges,proto3,oneof"`
}

func (*ClientTokenResponse_GrantedToken) isClientTokenResponse_Response() {}

func (*ClientTokenResponse_Challenges) isClientTokenResponse_Response() {}

type GrantedTokenResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Token               string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAfterSeconds int32                  `protobuf:"varint,2,opt,name=expires_after_seconds,json=expiresAfterSeconds,proto3" json:"expires_after_seconds,omitempty"`
	RefreshAfterSeconds int32                  `protobuf:"varint,3,opt,name=refresh_after_seconds,json=refreshAfterSeconds,proto3" json:"refresh_after_seconds,omitempty"`
	Domains             []*TokenDomain         `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GrantedTokenResponse) Reset() {
	*x = GrantedTokenResponse{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantedTokenResponse) ProtoMessage() {}

func (x *GrantedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantedTokenResponse.ProtoReflect.Descriptor instead.
func (*GrantedTokenResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{8}
}

func (x *GrantedTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GrantedTokenResponse) GetExpiresAfterSeconds() int32 {
	if x != nil {
		return x.ExpiresAfterSeconds
	}
	return 0
}

func (x *GrantedTokenResponse) GetRefreshAfterSeconds() int32 {
	if x != nil {
		return x.RefreshAfterSeconds
	}
	return 0
}

func (x *GrantedTokenResponse) GetDomains() []*TokenDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type TokenDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDomain) Reset() {
	*x = TokenDomain{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDomain) ProtoMessage() {}

func (x *TokenDomain) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDomain.ProtoReflect.Descriptor instead.
func (*TokenDomain) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{9}
}

func (x *TokenDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ChallengesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Challenges    []*Challenge           `protobuf:"bytes,2,rep,name=challenges,proto3" json:"challenges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengesResponse) Reset() {
	*x = ChallengesResponse{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengesResponse) ProtoMessage() {}

func (x *ChallengesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengesResponse.ProtoReflect.Descriptor instead.
func (*ChallengesResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{10}
}

func (x *ChallengesResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChallengesResponse) GetChallenges() []*Challenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Challenge:
	//
	//	*Challenge_HashCash
	//	*Challenge_Code
	//	*Challenge_EvaluateJs
	Challenge     isChallenge_Challenge `protobuf_oneof:"challenge"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{11}
}

func (x *Challenge) GetChallenge() isChallenge_Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *Challenge) GetHashCash() *HashCashChallenge {
	if x != nil {
		if x, ok := x.Challenge.(*Challenge_HashCash); ok {
			return x.HashCash
		}
	}
	return nil
}

func (x *Challenge) GetCode() *CodeChallenge {
	if x != nil {
		if x, ok := x.Challenge.(*Challenge_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *Challenge) GetEvaluateJs() *EvaluateJSChallenge {
	if x != nil {
		if x, ok := x.Challenge.(*Challenge_EvaluateJs); ok {
			return x.EvaluateJs
		}
	}
	return nil
}

type isChallenge_Challenge interface {
	isChallenge_Challenge()
}

type Challenge_HashCash struct {
	HashCash *HashCashChallenge `protobuf:"bytes,1,opt,name=hash_cash,json=hashCash,proto3,oneof"`
}

type Challenge_Code struct {
	Code *CodeChallenge `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type Challenge_EvaluateJs struct {
	EvaluateJs *EvaluateJSChallenge `protobuf:"bytes,3,opt,name=evaluate_js,json=evaluateJs,proto3,oneof"`
}

func (*Challenge_HashCash) isChallenge_Challenge() {}

func (*Challenge_Code) isChallenge_Challenge() {}

func (*Challenge_EvaluateJs) isChallenge_Challenge() {}

type HashCashChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashCashChallenge) Reset() {
	*x = HashCashChallenge{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashCashChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashCashChallenge) ProtoMessage() {}

func (x *HashCashChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashCashChallenge.ProtoReflect.Descriptor instead.
func (*HashCashChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{12}
}

func (x *HashCashChallenge) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *HashCashChallenge) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type CodeChallenge struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Method               string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Length               int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ExpiresIn            int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	CanonicalPhoneNumber string                 `protobuf:"bytes,4,opt,name=canonical_phone_number,json=canonicalPhoneNumber,proto3" json:"canonical_phone_number,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CodeChallenge) Reset() {
	*x = CodeChallenge{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeChallenge) ProtoMessage() {}

func (x *CodeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeChallenge.ProtoReflect.Descriptor instead.
func (*CodeChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{13}
}

func (x *CodeChallenge) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CodeChallenge) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CodeChallenge) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *CodeChallenge) GetCanonicalPhoneNumber() string {
	if x != nil {
		return x.CanonicalPhoneNumber
	}
	return ""
}

type EvaluateJSChallenge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LibrariesVersions []string               `protobuf:"bytes,2,rep,name=libraries_versions,json=librariesVersions,proto3" json:"libraries_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateJSChallenge) Reset() {
	*x = EvaluateJSChallenge{}
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateJSChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateJSChallenge) ProtoMessage() {}

func (x *EvaluateJSChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateJSChallenge.ProtoReflect.Descriptor instead.
func (*EvaluateJSChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluateJSChallenge) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EvaluateJSChallenge) GetLibrariesVersions() []string {
	if x != nil {
		return x.LibrariesVersions
	}
	return nil
}

var File_spotify_clienttoken_http_v0_clienttoken_proto protoreflect.FileDescriptor

const file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc = "" +
	"\n" +
	"-spotify/clienttoken/http/v0/clienttoken.proto\x12\x1bspotify.clienttoken.http.v0\x1a.spotify/clienttoken/data/v0/connectivity.proto\"\xaf\x02\n" +
	"\x12ClientTokenRequest\x12V\n" +
	"\frequest_type\x18\x01 \x01(\x0e23.spotify.clienttoken.http.v0.ClientTokenRequestTypeR\vrequestType\x12Q\n" +
	"\vclient_data\x18\x02 \x01(\v2..spotify.clienttoken.http.v0.ClientDataRequestH\x00R\n" +
	"clientData\x12c\n" +
	"\x11challenge_answers\x18\x03 \x01(\v24.spotify.clienttoken.http.v0.ChallengeAnswersRequestH\x00R\x10challengeAnswersB\t\n" +
	"\arequest\"\xc7\x01\n" +
	"\x11ClientDataRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12f\n" +
	"\x15connectivity_sdk_data\x18\x03 \x01(\v20.spotify.clienttoken.data.v0.ConnectivitySdkDataH\x00R\x13connectivitySdkDataB\x06\n" +
	"\x04data\"w\n" +
	"\x17ChallengeAnswersRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12F\n" +
	"\aanswers\x18\x02 \x03(\v2,.spotify.clienttoken.http.v0.ChallengeAnswerR\aanswers\"\xf8\x01\n" +
	"\x0fChallengeAnswer\x12J\n" +
	"\thash_cash\x18\x01 \x01(\v2+.spotify.clienttoken.http.v0.HashCashAnswerH\x00R\bhashCash\x12=\n" +
	"\x04code\x18\x02 \x01(\v2'.spotify.clienttoken.http.v0.CodeAnswerH\x00R\x04code\x12P\n" +
	"\vevaluate_js\x18\x03 \x01(\v2-.spotify.clienttoken.http.v0.EvaluateJSAnswerH\x00R\n" +
	"evaluateJsB\b\n" +
	"\x06answer\"D\n" +
	"\x0eHashCashAnswer\x12\x16\n" +
	"\x06suffix\x18\x01 \x01(\fR\x06suffix\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"\"\n" +
	"\n" +
	"CodeAnswer\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"*\n" +
	"\x10EvaluateJSAnswer\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xa9\x02\n" +
	"\x13ClientTokenResponse\x12Y\n" +
	"\rresponse_type\x18\x01 \x01(\x0e24.spotify.clienttoken.http.v0.ClientTokenResponseTypeR\fresponseType\x12X\n" +
	"\rgranted_token\x18\x02 \x01(\v21.spotify.clienttoken.http.v0.GrantedTokenResponseH\x00R\fgrantedToken\x12Q\n" +
	"\n" +
	"challenges\x18\x03 \x01(\v2/.spotify.clienttoken.http.v0.ChallengesResponseH\x00R\n" +
	"challengesB\n" +
	"\n" +
	"\bresponse\"\xd8\x01\n" +
	"\x14GrantedTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x122\n" +
	"\x15expires_after_seconds\x18\x02 \x01(\x05R\x13expiresAfterSeconds\x122\n" +
	"\x15refresh_after_seconds\x18\x03 \x01(\x05R\x13refreshAfterSeconds\x12B\n" +
	"\adomains\x18\x04 \x03(\v2(.spotify.clienttoken.http.v0.TokenDomainR\adomains\"%\n" +
	"\vTokenDomain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"r\n" +
	"\x12ChallengesResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12F\n" +
	"\n" +
	"challenges\x18\x02 \x03(\v2&.spotify.clienttoken.http.v0.ChallengeR\n" +
	"challenges\"\xfe\x01\n" +
	"\tChallenge\x12M\n" +
	"\thash_cash\x18\x01 \x01(\v2..spotify.clienttoken.http.v0.HashCashChallengeH\x00R\bhashCash\x12@\n" +
	"\x04code\x18\x02 \x01(\v2*.spotify.clienttoken.http.v0.CodeChallengeH\x00R\x04code\x12S\n" +
	"\vevaluate_js\x18\x03 \x01(\v20.spotify.clienttoken.http.v0.EvaluateJSChallengeH\x00R\n" +
	"evaluateJsB\v\n" +
	"\tchallenge\"C\n" +
	"\x11HashCashChallenge\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"\x94\x01\n" +
	"\rCodeChallenge\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x124\n" +
	"\x16canonical_phone_number\x18\x04 \x01(\tR\x14canonicalPhoneNumber\"X\n" +
	"\x13EvaluateJSChallenge\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12-\n" +
	"\x12libraries_versions\x18\x02 \x03(\tR\x11librariesVersions*u\n" +
	"\x16ClientTokenRequestType\x12\x13\n" +
	"\x0fREQUEST_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bREQUEST_CLIENT_DATA_REQUEST\x10\x01\x12%\n" +
	"!REQUEST_CHALLENGE_ANSWERS_REQUEST\x10\x02*v\n" +
	"\x17ClientTokenResponseType\x12\x14\n" +
	"\x10RESPONSE_UNKNOWN\x10\x00\x12#\n" +
	"\x1fRESPONSE_GRANTED_TOKEN_RESPONSE\x10\x01\x12 \n" +
	"\x1cRESPONSE_CHALLENGES_RESPONSE\x10\x02BGZEgithub.com/mcMineyC/spotcontrol/proto/spotify/clienttoken/http/v0b\x06proto3"

var (
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescOnce sync.Once
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData []byte
)

func file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP() []byte {
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescOnce.Do(func() {
		file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc), len(file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc)))
	})
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData
}

var file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes = []any{
	(ClientTokenRequestType)(0),     // 0: spotify.clienttoken.http.v0.ClientTokenRequestType
	(ClientTokenResponseType)(0),    // 1: spotify.clienttoken.http.v0.ClientTokenResponseType
	(*ClientTokenRequest)(nil),      // 2: spotify.clienttoken.http.v0.ClientTokenRequest
	(*ClientDataRequest)(nil),       // 3: spotify.clienttoken.http.v0.ClientDataRequest
	(*ChallengeAnswersRequest)(nil), // 4: spotify.clienttoken.http.v0.ChallengeAnswersRequest
	(*ChallengeAnswer)(nil),         // 5: spotify.clienttoken.http.v0.ChallengeAnswer
	(*HashCashAnswer)(nil),          // 6: spotify.clienttoken.http.v0.HashCashAnswer
	(*CodeAnswer)(nil),              // 7: spotify.clienttoken.http.v0.CodeAnswer
	(*EvaluateJSAnswer)(nil),        // 8: spotify.clienttoken.http.v0.EvaluateJSAnswer
	(*ClientTokenResponse)(nil),     // 9: spotify.clienttoken.http.v0.ClientTokenResponse
	(*GrantedTokenResponse)(nil),    // 10: spotify.clienttoken.http.v0.GrantedTokenResponse
	(*TokenDomain)(nil),             // 11: spotify.clienttoken.http.v0.TokenDomain
	(*ChallengesResponse)(nil),      // 12: spotify.clienttoken.http.v0.ChallengesResponse
	(*Challenge)(nil),               // 13: spotify.clienttoken.http.v0.Challenge
	(*HashCashChallenge)(nil),       // 14: spotify.clienttoken.http.v0.HashCashChallenge
	(*CodeChallenge)(nil),           // 15: spotify.clienttoken.http.v0.CodeChallenge
	(*EvaluateJSChallenge)(nil),     // 16: spotify.clienttoken.http.v0.EvaluateJSChallenge
	(*v0.ConnectivitySdkData)(nil),  // 17: spotify.clienttoken.data.v0.ConnectivitySdkData
}
var file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs = []int32{
	0,  // 0: spotify.clienttoken.http.v0.ClientTokenRequest.request_type:type_name -> spotify.clienttoken.http.v0.ClientTokenRequestType
	3,  // 1: spotify.clienttoken.http.v0.ClientTokenRequest.client_data:type_name -> spotify.clienttoken.http.v0.ClientDataRequest
	4,  // 2: spotify.clienttoken.http.v0.ClientTokenRequest.challenge_answers:type_name -> spotify.clienttoken.http.v0.ChallengeAnswersRequest
	17, // 3: spotify.clienttoken.http.v0.ClientDataRequest.connectivity_sdk_data:type_name -> spotify.clienttoken.data.v0.ConnectivitySdkData
	5,  // 4: spotify.clienttoken.http.v0.ChallengeAnswersRequest.answers:type_name -> spotify.clienttoken.http.v0.ChallengeAnswer
	6,  // 5: spotify.clienttoken.http.v0.ChallengeAnswer.hash_cash:type_name -> spotify.clienttoken.http.v0.HashCashAnswer
	7,  // 6: spotify.clienttoken.http.v0.ChallengeAnswer.code:type_name -> spotify.clienttoken.http.v0.CodeAnswer
	8,  // 7: spotify.clienttoken.http.v0.ChallengeAnswer.evaluate_js:type_name -> spotify.clienttoken.http.v0.EvaluateJSAnswer
	1,  // 8: spotify.clienttoken.http.v0.ClientTokenResponse.response_type:type_name -> spotify.clienttoken.http.v0.ClientTokenResponseType
	10, // 9: spotify.clienttoken.http.v0.ClientTokenResponse.granted_token:type_name -> spotify.clienttoken.http.v0.GrantedTokenResponse
	12, // 10: spotify.clienttoken.http.v0.ClientTokenResponse.challenges:type_name -> spotify.clienttoken.http.v0.ChallengesResponse
	11, // 11: spotify.clienttoken.http.v0.GrantedTokenResponse.domains:type_name -> spotify.clienttoken.http.v0.TokenDomain
	13, // 12: spotify.clienttoken.http.v0.ChallengesResponse.challenges:type_name -> spotify.clienttoken.http.v0.Challenge
	14, // 13: spotify.clienttoken.http.v0.Challenge.hash_cash:type_name -> spotify.clienttoken.http.v0.HashCashChallenge
	15, // 14: spotify.clienttoken.http.v0.Challenge.code:type_name -> spotify.clienttoken.http.v0.CodeChallenge
	16, // 15: spotify.clienttoken.http.v0.Challenge.evaluate_js:type_name -> spotify.clienttoken.http.v0.EvaluateJSChallenge
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_spotify_clienttoken_http_v0_clienttoken_proto_init() }
func file_spotify_clienttoken_http_v0_clienttoken_proto_init() {
	if File_spotify_clienttoken_http_v0_clienttoken_proto != nil {
		return
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientTokenRequest_ClientData)(nil),
		(*ClientTokenRequest_ChallengeAnswers)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientDataRequest_ConnectivitySdkData)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3].OneofWrappers = []any{
		(*ChallengeAnswer_HashCash)(nil),
		(*ChallengeAnswer_Code)(nil),
		(*ChallengeAnswer_EvaluateJs)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientTokenResponse_GrantedToken)(nil),
		(*ClientTokenResponse_Challenges)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11].OneofWrappers = []any{
		(*Challenge_HashCash)(nil),
		(*Challenge_Code)(nil),
		(*Challenge_EvaluateJs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc), len(file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes,
		DependencyIndexes: file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs,
		EnumInfos:         file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes,
		MessageInfos:      file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes,
	}.Build()
	File_spotify_clienttoken_http_v0_clienttoken_proto = out.File
	file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes = nil
	file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs = nil
}
