// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: spotify/clienttoken/http/v0/clienttoken.proto

package v0

import (
	v0 "github.com/mcMineyC/spotcontrol/proto/spotify/clienttoken/data/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientTokenRequestType int32

const (
	ClientTokenRequestType_REQUEST_UNKNOWN                   ClientTokenRequestType = 0
	ClientTokenRequestType_REQUEST_CLIENT_DATA_REQUEST       ClientTokenRequestType = 1
	ClientTokenRequestType_REQUEST_CHALLENGE_ANSWERS_REQUEST ClientTokenRequestType = 2
)

// Enum value maps for ClientTokenRequestType.
var (
	ClientTokenRequestType_name = map[int32]string{
		0: "REQUEST_UNKNOWN",
		1: "REQUEST_CLIENT_DATA_REQUEST",
		2: "REQUEST_CHALLENGE_ANSWERS_REQUEST",
	}
	ClientTokenRequestType_value = map[string]int32{
		"REQUEST_UNKNOWN":                   0,
		"REQUEST_CLIENT_DATA_REQUEST":       1,
		"REQUEST_CHALLENGE_ANSWERS_REQUEST": 2,
	}
)

func (x ClientTokenRequestType) Enum() *ClientTokenRequestType {
	p := new(ClientTokenRequestType)
	*p = x
	return p
}

func (x ClientTokenRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTokenRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[0].Descriptor()
}

func (ClientTokenRequestType) Type() protoreflect.EnumType {
	return &file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[0]
}

func (x ClientTokenRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTokenRequestType.Descriptor instead.
func (ClientTokenRequestType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{0}
}

type ClientTokenResponseType int32

const (
	ClientTokenResponseType_RESPONSE_UNKNOWN                ClientTokenResponseType = 0
	ClientTokenResponseType_RESPONSE_GRANTED_TOKEN_RESPONSE ClientTokenResponseType = 1
	ClientTokenResponseType_RESPONSE_CHALLENGES_RESPONSE    ClientTokenResponseType = 2
)

// Enum value maps for ClientTokenResponseType.
var (
	ClientTokenResponseType_name = map[int32]string{
		0: "RESPONSE_UNKNOWN",
		1: "RESPONSE_GRANTED_TOKEN_RESPONSE",
		2: "RESPONSE_CHALLENGES_RESPONSE",
	}
	ClientTokenResponseType_value = map[string]int32{
		"RESPONSE_UNKNOWN":                0,
		"RESPONSE_GRANTED_TOKEN_RESPONSE": 1,
		"RESPONSE_CHALLENGES_RESPONSE":    2,
	}
)

func (x ClientTokenResponseType) Enum() *ClientTokenResponseType {
	p := new(ClientTokenResponseType)
	*p = x
	return p
}

func (x ClientTokenResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTokenResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[1].Descriptor()
}

func (ClientTokenResponseType) Type() protoreflect.EnumType {
	return &file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes[1]
}

func (x ClientTokenResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTokenResponseType.Descriptor instead.
func (ClientTokenResponseType) EnumDescriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{1}
}

type ClientTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestType ClientTokenRequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=spotify.clienttoken.http.v0.ClientTokenRequestType" json:"request_type,omitempty"`
	// Types that are assignable to Request:
	//
	//	*ClientTokenRequest_ClientData
	//	*ClientTokenRequest_ChallengeAnswers
	Request isClientTokenRequest_Request `protobuf_oneof:"request"`
}

func (x *ClientTokenRequest) Reset() {
	*x = ClientTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTokenRequest) ProtoMessage() {}

func (x *ClientTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTokenRequest.ProtoReflect.Descriptor instead.
func (*ClientTokenRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{0}
}

func (x *ClientTokenRequest) GetRequestType() ClientTokenRequestType {
	if x != nil {
		return x.RequestType
	}
	return ClientTokenRequestType_REQUEST_UNKNOWN
}

func (m *ClientTokenRequest) GetRequest() isClientTokenRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientTokenRequest) GetClientData() *ClientDataRequest {
	if x, ok := x.GetRequest().(*ClientTokenRequest_ClientData); ok {
		return x.ClientData
	}
	return nil
}

func (x *ClientTokenRequest) GetChallengeAnswers() *ChallengeAnswersRequest {
	if x, ok := x.GetRequest().(*ClientTokenRequest_ChallengeAnswers); ok {
		return x.ChallengeAnswers
	}
	return nil
}

type isClientTokenRequest_Request interface {
	isClientTokenRequest_Request()
}

type ClientTokenRequest_ClientData struct {
	ClientData *ClientDataRequest `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3,oneof"`
}

type ClientTokenRequest_ChallengeAnswers struct {
	ChallengeAnswers *ChallengeAnswersRequest `protobuf:"bytes,3,opt,name=challenge_answers,json=challengeAnswers,proto3,oneof"`
}

func (*ClientTokenRequest_ClientData) isClientTokenRequest_Request() {}

func (*ClientTokenRequest_ChallengeAnswers) isClientTokenRequest_Request() {}

type ClientDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Types that are assignable to Data:
	//
	//	*ClientDataRequest_ConnectivitySdkData
	Data isClientDataRequest_Data `protobuf_oneof:"data"`
}

func (x *ClientDataRequest) Reset() {
	*x = ClientDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataRequest) ProtoMessage() {}

func (x *ClientDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataRequest.ProtoReflect.Descriptor instead.
func (*ClientDataRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDataRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientDataRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (m *ClientDataRequest) GetData() isClientDataRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ClientDataRequest) GetConnectivitySdkData() *v0.ConnectivitySdkData {
	if x, ok := x.GetData().(*ClientDataRequest_ConnectivitySdkData); ok {
		return x.ConnectivitySdkData
	}
	return nil
}

type isClientDataRequest_Data interface {
	isClientDataRequest_Data()
}

type ClientDataRequest_ConnectivitySdkData struct {
	ConnectivitySdkData *v0.ConnectivitySdkData `protobuf:"bytes,3,opt,name=connectivity_sdk_data,json=connectivitySdkData,proto3,oneof"`
}

func (*ClientDataRequest_ConnectivitySdkData) isClientDataRequest_Data() {}

type ChallengeAnswersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   string             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Answers []*ChallengeAnswer `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *ChallengeAnswersRequest) Reset() {
	*x = ChallengeAnswersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeAnswersRequest) ProtoMessage() {}

func (x *ChallengeAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeAnswersRequest.ProtoReflect.Descriptor instead.
func (*ChallengeAnswersRequest) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeAnswersRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChallengeAnswersRequest) GetAnswers() []*ChallengeAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type ChallengeAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Answer:
	//
	//	*ChallengeAnswer_HashCash
	//	*ChallengeAnswer_Code
	//	*ChallengeAnswer_EvaluateJs
	Answer isChallengeAnswer_Answer `protobuf_oneof:"answer"`
}

func (x *ChallengeAnswer) Reset() {
	*x = ChallengeAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeAnswer) ProtoMessage() {}

func (x *ChallengeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeAnswer.ProtoReflect.Descriptor instead.
func (*ChallengeAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{3}
}

func (m *ChallengeAnswer) GetAnswer() isChallengeAnswer_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (x *ChallengeAnswer) GetHashCash() *HashCashAnswer {
	if x, ok := x.GetAnswer().(*ChallengeAnswer_HashCash); ok {
		return x.HashCash
	}
	return nil
}

func (x *ChallengeAnswer) GetCode() *CodeAnswer {
	if x, ok := x.GetAnswer().(*ChallengeAnswer_Code); ok {
		return x.Code
	}
	return nil
}

func (x *ChallengeAnswer) GetEvaluateJs() *EvaluateJSAnswer {
	if x, ok := x.GetAnswer().(*ChallengeAnswer_EvaluateJs); ok {
		return x.EvaluateJs
	}
	return nil
}

type isChallengeAnswer_Answer interface {
	isChallengeAnswer_Answer()
}

type ChallengeAnswer_HashCash struct {
	HashCash *HashCashAnswer `protobuf:"bytes,1,opt,name=hash_cash,json=hashCash,proto3,oneof"`
}

type ChallengeAnswer_Code struct {
	Code *CodeAnswer `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type ChallengeAnswer_EvaluateJs struct {
	EvaluateJs *EvaluateJSAnswer `protobuf:"bytes,3,opt,name=evaluate_js,json=evaluateJs,proto3,oneof"`
}

func (*ChallengeAnswer_HashCash) isChallengeAnswer_Answer() {}

func (*ChallengeAnswer_Code) isChallengeAnswer_Answer() {}

func (*ChallengeAnswer_EvaluateJs) isChallengeAnswer_Answer() {}

type HashCashAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suffix   []byte `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *HashCashAnswer) Reset() {
	*x = HashCashAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashCashAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashCashAnswer) ProtoMessage() {}

func (x *HashCashAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashCashAnswer.ProtoReflect.Descriptor instead.
func (*HashCashAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{4}
}

func (x *HashCashAnswer) GetSuffix() []byte {
	if x != nil {
		return x.Suffix
	}
	return nil
}

func (x *HashCashAnswer) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CodeAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CodeAnswer) Reset() {
	*x = CodeAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAnswer) ProtoMessage() {}

func (x *CodeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAnswer.ProtoReflect.Descriptor instead.
func (*CodeAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{5}
}

func (x *CodeAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EvaluateJSAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EvaluateJSAnswer) Reset() {
	*x = EvaluateJSAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateJSAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateJSAnswer) ProtoMessage() {}

func (x *EvaluateJSAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateJSAnswer.ProtoReflect.Descriptor instead.
func (*EvaluateJSAnswer) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateJSAnswer) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ClientTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseType ClientTokenResponseType `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=spotify.clienttoken.http.v0.ClientTokenResponseType" json:"response_type,omitempty"`
	// Types that are assignable to Response:
	//
	//	*ClientTokenResponse_GrantedToken
	//	*ClientTokenResponse_Challenges
	Response isClientTokenResponse_Response `protobuf_oneof:"response"`
}

func (x *ClientTokenResponse) Reset() {
	*x = ClientTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTokenResponse) ProtoMessage() {}

func (x *ClientTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTokenResponse.ProtoReflect.Descriptor instead.
func (*ClientTokenResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{7}
}

func (x *ClientTokenResponse) GetResponseType() ClientTokenResponseType {
	if x != nil {
		return x.ResponseType
	}
	return ClientTokenResponseType_RESPONSE_UNKNOWN
}

func (m *ClientTokenResponse) GetResponse() isClientTokenResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ClientTokenResponse) GetGrantedToken() *GrantedTokenResponse {
	if x, ok := x.GetResponse().(*ClientTokenResponse_GrantedToken); ok {
		return x.GrantedToken
	}
	return nil
}

func (x *ClientTokenResponse) GetChallenges() *ChallengesResponse {
	if x, ok := x.GetResponse().(*ClientTokenResponse_Challenges); ok {
		return x.Challenges
	}
	return nil
}

type isClientTokenResponse_Response interface {
	isClientTokenResponse_Response()
}

type ClientTokenResponse_GrantedToken struct {
	GrantedToken *GrantedTokenResponse `protobuf:"bytes,2,opt,name=granted_token,json=grantedToken,proto3,oneof"`
}

type ClientTokenResponse_Challenges struct {
	Challenges *ChallengesResponse `protobuf:"bytes,3,opt,name=challenges,proto3,oneof"`
}

func (*ClientTokenResponse_GrantedToken) isClientTokenResponse_Response() {}

func (*ClientTokenResponse_Challenges) isClientTokenResponse_Response() {}

type GrantedTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token               string         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAfterSeconds int32          `protobuf:"varint,2,opt,name=expires_after_seconds,json=expiresAfterSeconds,proto3" json:"expires_after_seconds,omitempty"`
	RefreshAfterSeconds int32          `protobuf:"varint,3,opt,name=refresh_after_seconds,json=refreshAfterSeconds,proto3" json:"refresh_after_seconds,omitempty"`
	Domains             []*TokenDomain `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *GrantedTokenResponse) Reset() {
	*x = GrantedTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantedTokenResponse) ProtoMessage() {}

func (x *GrantedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantedTokenResponse.ProtoReflect.Descriptor instead.
func (*GrantedTokenResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{8}
}

func (x *GrantedTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GrantedTokenResponse) GetExpiresAfterSeconds() int32 {
	if x != nil {
		return x.ExpiresAfterSeconds
	}
	return 0
}

func (x *GrantedTokenResponse) GetRefreshAfterSeconds() int32 {
	if x != nil {
		return x.RefreshAfterSeconds
	}
	return 0
}

func (x *GrantedTokenResponse) GetDomains() []*TokenDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type TokenDomain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *TokenDomain) Reset() {
	*x = TokenDomain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDomain) ProtoMessage() {}

func (x *TokenDomain) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDomain.ProtoReflect.Descriptor instead.
func (*TokenDomain) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{9}
}

func (x *TokenDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ChallengesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      string       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Challenges []*Challenge `protobuf:"bytes,2,rep,name=challenges,proto3" json:"challenges,omitempty"`
}

func (x *ChallengesResponse) Reset() {
	*x = ChallengesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengesResponse) ProtoMessage() {}

func (x *ChallengesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengesResponse.ProtoReflect.Descriptor instead.
func (*ChallengesResponse) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{10}
}

func (x *ChallengesResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChallengesResponse) GetChallenges() []*Challenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

type Challenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Challenge:
	//
	//	*Challenge_HashCash
	//	*Challenge_Code
	//	*Challenge_EvaluateJs
	Challenge isChallenge_Challenge `protobuf_oneof:"challenge"`
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{11}
}

func (m *Challenge) GetChallenge() isChallenge_Challenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (x *Challenge) GetHashCash() *HashCashChallenge {
	if x, ok := x.GetChallenge().(*Challenge_HashCash); ok {
		return x.HashCash
	}
	return nil
}

func (x *Challenge) GetCode() *CodeChallenge {
	if x, ok := x.GetChallenge().(*Challenge_Code); ok {
		return x.Code
	}
	return nil
}

func (x *Challenge) GetEvaluateJs() *EvaluateJSChallenge {
	if x, ok := x.GetChallenge().(*Challenge_EvaluateJs); ok {
		return x.EvaluateJs
	}
	return nil
}

type isChallenge_Challenge interface {
	isChallenge_Challenge()
}

type Challenge_HashCash struct {
	HashCash *HashCashChallenge `protobuf:"bytes,1,opt,name=hash_cash,json=hashCash,proto3,oneof"`
}

type Challenge_Code struct {
	Code *CodeChallenge `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type Challenge_EvaluateJs struct {
	EvaluateJs *EvaluateJSChallenge `protobuf:"bytes,3,opt,name=evaluate_js,json=evaluateJs,proto3,oneof"`
}

func (*Challenge_HashCash) isChallenge_Challenge() {}

func (*Challenge_Code) isChallenge_Challenge() {}

func (*Challenge_EvaluateJs) isChallenge_Challenge() {}

type HashCashChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Length int32  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *HashCashChallenge) Reset() {
	*x = HashCashChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashCashChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashCashChallenge) ProtoMessage() {}

func (x *HashCashChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashCashChallenge.ProtoReflect.Descriptor instead.
func (*HashCashChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{12}
}

func (x *HashCashChallenge) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *HashCashChallenge) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type CodeChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method               string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Length               int32  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ExpiresIn            int64  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	CanonicalPhoneNumber string `protobuf:"bytes,4,opt,name=canonical_phone_number,json=canonicalPhoneNumber,proto3" json:"canonical_phone_number,omitempty"`
}

func (x *CodeChallenge) Reset() {
	*x = CodeChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeChallenge) ProtoMessage() {}

func (x *CodeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeChallenge.ProtoReflect.Descriptor instead.
func (*CodeChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{13}
}

func (x *CodeChallenge) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CodeChallenge) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CodeChallenge) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *CodeChallenge) GetCanonicalPhoneNumber() string {
	if x != nil {
		return x.CanonicalPhoneNumber
	}
	return ""
}

type EvaluateJSChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code              string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LibrariesVersions []string `protobuf:"bytes,2,rep,name=libraries_versions,json=librariesVersions,proto3" json:"libraries_versions,omitempty"`
}

func (x *EvaluateJSChallenge) Reset() {
	*x = EvaluateJSChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateJSChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateJSChallenge) ProtoMessage() {}

func (x *EvaluateJSChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateJSChallenge.ProtoReflect.Descriptor instead.
func (*EvaluateJSChallenge) Descriptor() ([]byte, []int) {
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluateJSChallenge) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EvaluateJSChallenge) GetLibrariesVersions() []string {
	if x != nil {
		return x.LibrariesVersions
	}
	return nil
}

var File_spotify_clienttoken_http_v0_clienttoken_proto protoreflect.FileDescriptor

var file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x76, 0x30, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1b, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x1a, 0x2e, 0x73, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76, 0x30, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x02, 0x0a,
	0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x51, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x63,
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x10, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc7,
	0x01, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x66, 0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x64, 0x6b, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x53, 0x64, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x13, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x64, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x77, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x70, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x22, 0xf8, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x63, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73, 0x68, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73,
	0x68, 0x12, 0x3d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x50, 0x0a, 0x0b, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x5f, 0x6a, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x76, 0x30, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4a, 0x53, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x4a, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0e,
	0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73, 0x68, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0a, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x4a, 0x53, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xa9, 0x02, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x34, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x73,
	0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x51, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76,
	0x30, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd8,
	0x01, 0x0a, 0x14, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x32, 0x0a,
	0x15, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x12, 0x32, 0x0a, 0x15, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x61, 0x66, 0x74,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x13, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x66, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x72, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x73, 0x22, 0xfe, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x12, 0x4d, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x63, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x76, 0x30, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73, 0x68, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73,
	0x68, 0x12, 0x40, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x53, 0x0a, 0x0b, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x5f,
	0x6a, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4a,
	0x53, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4a, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x73,
	0x68, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x94, 0x01, 0x0a, 0x0d, 0x43,
	0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x34, 0x0a, 0x16, 0x63,
	0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x61, 0x6e,
	0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x58, 0x0a, 0x13, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x4a, 0x53, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x12,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x75, 0x0a, 0x16, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x25, 0x0a, 0x21, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45, 0x4e, 0x47, 0x45,
	0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x10, 0x02, 0x2a, 0x76, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f,
	0x47, 0x52, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x52, 0x45, 0x53, 0x50,
	0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45, 0x4e, 0x47, 0x45, 0x53, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x4d, 0x69, 0x6e, 0x65, 0x79,
	0x43, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x76, 0x30, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescOnce sync.Once
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData = file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc
)

func file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescGZIP() []byte {
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescOnce.Do(func() {
		file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData = protoimpl.X.CompressGZIP(file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData)
	})
	return file_spotify_clienttoken_http_v0_clienttoken_proto_rawDescData
}

var file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes = []any{
	(ClientTokenRequestType)(0),     // 0: spotify.clienttoken.http.v0.ClientTokenRequestType
	(ClientTokenResponseType)(0),    // 1: spotify.clienttoken.http.v0.ClientTokenResponseType
	(*ClientTokenRequest)(nil),      // 2: spotify.clienttoken.http.v0.ClientTokenRequest
	(*ClientDataRequest)(nil),       // 3: spotify.clienttoken.http.v0.ClientDataRequest
	(*ChallengeAnswersRequest)(nil), // 4: spotify.clienttoken.http.v0.ChallengeAnswersRequest
	(*ChallengeAnswer)(nil),         // 5: spotify.clienttoken.http.v0.ChallengeAnswer
	(*HashCashAnswer)(nil),          // 6: spotify.clienttoken.http.v0.HashCashAnswer
	(*CodeAnswer)(nil),              // 7: spotify.clienttoken.http.v0.CodeAnswer
	(*EvaluateJSAnswer)(nil),        // 8: spotify.clienttoken.http.v0.EvaluateJSAnswer
	(*ClientTokenResponse)(nil),     // 9: spotify.clienttoken.http.v0.ClientTokenResponse
	(*GrantedTokenResponse)(nil),    // 10: spotify.clienttoken.http.v0.GrantedTokenResponse
	(*TokenDomain)(nil),             // 11: spotify.clienttoken.http.v0.TokenDomain
	(*ChallengesResponse)(nil),      // 12: spotify.clienttoken.http.v0.ChallengesResponse
	(*Challenge)(nil),               // 13: spotify.clienttoken.http.v0.Challenge
	(*HashCashChallenge)(nil),       // 14: spotify.clienttoken.http.v0.HashCashChallenge
	(*CodeChallenge)(nil),           // 15: spotify.clienttoken.http.v0.CodeChallenge
	(*EvaluateJSChallenge)(nil),     // 16: spotify.clienttoken.http.v0.EvaluateJSChallenge
	(*v0.ConnectivitySdkData)(nil),  // 17: spotify.clienttoken.data.v0.ConnectivitySdkData
}
var file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs = []int32{
	0,  // 0: spotify.clienttoken.http.v0.ClientTokenRequest.request_type:type_name -> spotify.clienttoken.http.v0.ClientTokenRequestType
	3,  // 1: spotify.clienttoken.http.v0.ClientTokenRequest.client_data:type_name -> spotify.clienttoken.http.v0.ClientDataRequest
	4,  // 2: spotify.clienttoken.http.v0.ClientTokenRequest.challenge_answers:type_name -> spotify.clienttoken.http.v0.ChallengeAnswersRequest
	17, // 3: spotify.clienttoken.http.v0.ClientDataRequest.connectivity_sdk_data:type_name -> spotify.clienttoken.data.v0.ConnectivitySdkData
	5,  // 4: spotify.clienttoken.http.v0.ChallengeAnswersRequest.answers:type_name -> spotify.clienttoken.http.v0.ChallengeAnswer
	6,  // 5: spotify.clienttoken.http.v0.ChallengeAnswer.hash_cash:type_name -> spotify.clienttoken.http.v0.HashCashAnswer
	7,  // 6: spotify.clienttoken.http.v0.ChallengeAnswer.code:type_name -> spotify.clienttoken.http.v0.CodeAnswer
	8,  // 7: spotify.clienttoken.http.v0.ChallengeAnswer.evaluate_js:type_name -> spotify.clienttoken.http.v0.EvaluateJSAnswer
	1,  // 8: spotify.clienttoken.http.v0.ClientTokenResponse.response_type:type_name -> spotify.clienttoken.http.v0.ClientTokenResponseType
	10, // 9: spotify.clienttoken.http.v0.ClientTokenResponse.granted_token:type_name -> spotify.clienttoken.http.v0.GrantedTokenResponse
	12, // 10: spotify.clienttoken.http.v0.ClientTokenResponse.challenges:type_name -> spotify.clienttoken.http.v0.ChallengesResponse
	11, // 11: spotify.clienttoken.http.v0.GrantedTokenResponse.domains:type_name -> spotify.clienttoken.http.v0.TokenDomain
	13, // 12: spotify.clienttoken.http.v0.ChallengesResponse.challenges:type_name -> spotify.clienttoken.http.v0.Challenge
	14, // 13: spotify.clienttoken.http.v0.Challenge.hash_cash:type_name -> spotify.clienttoken.http.v0.HashCashChallenge
	15, // 14: spotify.clienttoken.http.v0.Challenge.code:type_name -> spotify.clienttoken.http.v0.CodeChallenge
	16, // 15: spotify.clienttoken.http.v0.Challenge.evaluate_js:type_name -> spotify.clienttoken.http.v0.EvaluateJSChallenge
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_spotify_clienttoken_http_v0_clienttoken_proto_init() }
func file_spotify_clienttoken_http_v0_clienttoken_proto_init() {
	if File_spotify_clienttoken_http_v0_clienttoken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ClientTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ClientDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ChallengeAnswersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ChallengeAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*HashCashAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CodeAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluateJSAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ClientTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GrantedTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*TokenDomain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ChallengesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Challenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*HashCashChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CodeChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluateJSChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientTokenRequest_ClientData)(nil),
		(*ClientTokenRequest_ChallengeAnswers)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientDataRequest_ConnectivitySdkData)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[3].OneofWrappers = []any{
		(*ChallengeAnswer_HashCash)(nil),
		(*ChallengeAnswer_Code)(nil),
		(*ChallengeAnswer_EvaluateJs)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientTokenResponse_GrantedToken)(nil),
		(*ClientTokenResponse_Challenges)(nil),
	}
	file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes[11].OneofWrappers = []any{
		(*Challenge_HashCash)(nil),
		(*Challenge_Code)(nil),
		(*Challenge_EvaluateJs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes,
		DependencyIndexes: file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs,
		EnumInfos:         file_spotify_clienttoken_http_v0_clienttoken_proto_enumTypes,
		MessageInfos:      file_spotify_clienttoken_http_v0_clienttoken_proto_msgTypes,
	}.Build()
	File_spotify_clienttoken_http_v0_clienttoken_proto = out.File
	file_spotify_clienttoken_http_v0_clienttoken_proto_rawDesc = nil
	file_spotify_clienttoken_http_v0_clienttoken_proto_goTypes = nil
	file_spotify_clienttoken_http_v0_clienttoken_proto_depIdxs = nil
}
