// Extracted from: Spotify 1.2.52.442 (windows)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/your_library/your_library_request.proto

package your_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CuratedItems_CuratedItemsFilter int32

const (
	CuratedItems_NONE             CuratedItems_CuratedItemsFilter = 0
	CuratedItems_GROUP_BY         CuratedItems_CuratedItemsFilter = 1
	CuratedItems_ONLY_CURATED     CuratedItems_CuratedItemsFilter = 2
	CuratedItems_ONLY_NOT_CURATED CuratedItems_CuratedItemsFilter = 3
)

// Enum value maps for CuratedItems_CuratedItemsFilter.
var (
	CuratedItems_CuratedItemsFilter_name = map[int32]string{
		0: "NONE",
		1: "GROUP_BY",
		2: "ONLY_CURATED",
		3: "ONLY_NOT_CURATED",
	}
	CuratedItems_CuratedItemsFilter_value = map[string]int32{
		"NONE":             0,
		"GROUP_BY":         1,
		"ONLY_CURATED":     2,
		"ONLY_NOT_CURATED": 3,
	}
)

func (x CuratedItems_CuratedItemsFilter) Enum() *CuratedItems_CuratedItemsFilter {
	p := new(CuratedItems_CuratedItemsFilter)
	*p = x
	return p
}

func (x CuratedItems_CuratedItemsFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CuratedItems_CuratedItemsFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_your_library_your_library_request_proto_enumTypes[0].Descriptor()
}

func (CuratedItems_CuratedItemsFilter) Type() protoreflect.EnumType {
	return &file_spotify_your_library_your_library_request_proto_enumTypes[0]
}

func (x CuratedItems_CuratedItemsFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CuratedItems_CuratedItemsFilter.Descriptor instead.
func (CuratedItems_CuratedItemsFilter) EnumDescriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_request_proto_rawDescGZIP(), []int{1, 0}
}

type YourLibraryTagFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagUri        string                 `protobuf:"bytes,1,opt,name=tag_uri,json=tagUri,proto3" json:"tag_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryTagFilter) Reset() {
	*x = YourLibraryTagFilter{}
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryTagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryTagFilter) ProtoMessage() {}

func (x *YourLibraryTagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryTagFilter.ProtoReflect.Descriptor instead.
func (*YourLibraryTagFilter) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_request_proto_rawDescGZIP(), []int{0}
}

func (x *YourLibraryTagFilter) GetTagUri() string {
	if x != nil {
		return x.TagUri
	}
	return ""
}

type CuratedItems struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         []string                        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Filter        CuratedItems_CuratedItemsFilter `protobuf:"varint,2,opt,name=filter,proto3,enum=spotify.your_library.proto.CuratedItems_CuratedItemsFilter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CuratedItems) Reset() {
	*x = CuratedItems{}
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CuratedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuratedItems) ProtoMessage() {}

func (x *CuratedItems) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CuratedItems.ProtoReflect.Descriptor instead.
func (*CuratedItems) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_request_proto_rawDescGZIP(), []int{1}
}

func (x *CuratedItems) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CuratedItems) GetFilter() CuratedItems_CuratedItemsFilter {
	if x != nil {
		return x.Filter
	}
	return CuratedItems_NONE
}

type YourLibraryRequestHeader struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RemainingEntities       bool                   `protobuf:"varint,9,opt,name=remaining_entities,json=remainingEntities,proto3" json:"remaining_entities,omitempty"`
	TotalCount              bool                   `protobuf:"varint,18,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	LowerBound              string                 `protobuf:"bytes,10,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	Skip                    int32                  `protobuf:"varint,11,opt,name=skip,proto3" json:"skip,omitempty"`
	Length                  int32                  `protobuf:"varint,12,opt,name=length,proto3" json:"length,omitempty"`
	TextFilter              string                 `protobuf:"bytes,13,opt,name=text_filter,json=textFilter,proto3" json:"text_filter,omitempty"`
	Filters                 *YourLibraryFilters    `protobuf:"bytes,14,opt,name=filters,proto3" json:"filters,omitempty"`
	SortOrder               *YourLibrarySortOrder  `protobuf:"bytes,15,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	AllPlaylists            bool                   `protobuf:"varint,17,opt,name=all_playlists,json=allPlaylists,proto3" json:"all_playlists,omitempty"`
	FillFolders             []int64                `protobuf:"varint,34,rep,packed,name=fill_folders,json=fillFolders,proto3" json:"fill_folders,omitempty"`
	SeparatePinnedItems     bool                   `protobuf:"varint,22,opt,name=separate_pinned_items,json=separatePinnedItems,proto3" json:"separate_pinned_items,omitempty"`
	NumLinkTypesInPlaylists bool                   `protobuf:"varint,25,opt,name=num_link_types_in_playlists,json=numLinkTypesInPlaylists,proto3" json:"num_link_types_in_playlists,omitempty"`
	IgnorePinning           bool                   `protobuf:"varint,26,opt,name=ignore_pinning,json=ignorePinning,proto3" json:"ignore_pinning,omitempty"`
	CuratedItems            *CuratedItems          `protobuf:"bytes,29,opt,name=curated_items,json=curatedItems,proto3" json:"curated_items,omitempty"`
	IncludeEvents           bool                   `protobuf:"varint,30,opt,name=include_events,json=includeEvents,proto3" json:"include_events,omitempty"`
	IncludePrereleases      bool                   `protobuf:"varint,31,opt,name=include_prereleases,json=includePrereleases,proto3" json:"include_prereleases,omitempty"`
	IncludeAuthors          bool                   `protobuf:"varint,33,opt,name=include_authors,json=includeAuthors,proto3" json:"include_authors,omitempty"`
	// Types that are valid to be assigned to MaybeFolderId:
	//
	//	*YourLibraryRequestHeader_FolderId
	MaybeFolderId isYourLibraryRequestHeader_MaybeFolderId `protobuf_oneof:"maybe_folder_id"`
	// Types that are valid to be assigned to MaybeTagFilter:
	//
	//	*YourLibraryRequestHeader_TagFilter
	MaybeTagFilter isYourLibraryRequestHeader_MaybeTagFilter `protobuf_oneof:"maybe_tag_filter"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *YourLibraryRequestHeader) Reset() {
	*x = YourLibraryRequestHeader{}
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryRequestHeader) ProtoMessage() {}

func (x *YourLibraryRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryRequestHeader.ProtoReflect.Descriptor instead.
func (*YourLibraryRequestHeader) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_request_proto_rawDescGZIP(), []int{2}
}

func (x *YourLibraryRequestHeader) GetRemainingEntities() bool {
	if x != nil {
		return x.RemainingEntities
	}
	return false
}

func (x *YourLibraryRequestHeader) GetTotalCount() bool {
	if x != nil {
		return x.TotalCount
	}
	return false
}

func (x *YourLibraryRequestHeader) GetLowerBound() string {
	if x != nil {
		return x.LowerBound
	}
	return ""
}

func (x *YourLibraryRequestHeader) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *YourLibraryRequestHeader) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *YourLibraryRequestHeader) GetTextFilter() string {
	if x != nil {
		return x.TextFilter
	}
	return ""
}

func (x *YourLibraryRequestHeader) GetFilters() *YourLibraryFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetSortOrder() *YourLibrarySortOrder {
	if x != nil {
		return x.SortOrder
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetAllPlaylists() bool {
	if x != nil {
		return x.AllPlaylists
	}
	return false
}

func (x *YourLibraryRequestHeader) GetFillFolders() []int64 {
	if x != nil {
		return x.FillFolders
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetSeparatePinnedItems() bool {
	if x != nil {
		return x.SeparatePinnedItems
	}
	return false
}

func (x *YourLibraryRequestHeader) GetNumLinkTypesInPlaylists() bool {
	if x != nil {
		return x.NumLinkTypesInPlaylists
	}
	return false
}

func (x *YourLibraryRequestHeader) GetIgnorePinning() bool {
	if x != nil {
		return x.IgnorePinning
	}
	return false
}

func (x *YourLibraryRequestHeader) GetCuratedItems() *CuratedItems {
	if x != nil {
		return x.CuratedItems
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetIncludeEvents() bool {
	if x != nil {
		return x.IncludeEvents
	}
	return false
}

func (x *YourLibraryRequestHeader) GetIncludePrereleases() bool {
	if x != nil {
		return x.IncludePrereleases
	}
	return false
}

func (x *YourLibraryRequestHeader) GetIncludeAuthors() bool {
	if x != nil {
		return x.IncludeAuthors
	}
	return false
}

func (x *YourLibraryRequestHeader) GetMaybeFolderId() isYourLibraryRequestHeader_MaybeFolderId {
	if x != nil {
		return x.MaybeFolderId
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetFolderId() int64 {
	if x != nil {
		if x, ok := x.MaybeFolderId.(*YourLibraryRequestHeader_FolderId); ok {
			return x.FolderId
		}
	}
	return 0
}

func (x *YourLibraryRequestHeader) GetMaybeTagFilter() isYourLibraryRequestHeader_MaybeTagFilter {
	if x != nil {
		return x.MaybeTagFilter
	}
	return nil
}

func (x *YourLibraryRequestHeader) GetTagFilter() *YourLibraryTagFilter {
	if x != nil {
		if x, ok := x.MaybeTagFilter.(*YourLibraryRequestHeader_TagFilter); ok {
			return x.TagFilter
		}
	}
	return nil
}

type isYourLibraryRequestHeader_MaybeFolderId interface {
	isYourLibraryRequestHeader_MaybeFolderId()
}

type YourLibraryRequestHeader_FolderId struct {
	FolderId int64 `protobuf:"varint,16,opt,name=folder_id,json=folderId,proto3,oneof"`
}

func (*YourLibraryRequestHeader_FolderId) isYourLibraryRequestHeader_MaybeFolderId() {}

type isYourLibraryRequestHeader_MaybeTagFilter interface {
	isYourLibraryRequestHeader_MaybeTagFilter()
}

type YourLibraryRequestHeader_TagFilter struct {
	TagFilter *YourLibraryTagFilter `protobuf:"bytes,24,opt,name=tag_filter,json=tagFilter,proto3,oneof"`
}

func (*YourLibraryRequestHeader_TagFilter) isYourLibraryRequestHeader_MaybeTagFilter() {}

type YourLibraryRequest struct {
	state                protoimpl.MessageState           `protogen:"open.v1"`
	Header               *YourLibraryRequestHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PseudoPlaylistConfig *YourLibraryPseudoPlaylistConfig `protobuf:"bytes,4,opt,name=pseudo_playlist_config,json=pseudoPlaylistConfig,proto3" json:"pseudo_playlist_config,omitempty"`
	UpdateThrottling     int32                            `protobuf:"varint,5,opt,name=update_throttling,json=updateThrottling,proto3" json:"update_throttling,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *YourLibraryRequest) Reset() {
	*x = YourLibraryRequest{}
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryRequest) ProtoMessage() {}

func (x *YourLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryRequest.ProtoReflect.Descriptor instead.
func (*YourLibraryRequest) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_request_proto_rawDescGZIP(), []int{3}
}

func (x *YourLibraryRequest) GetHeader() *YourLibraryRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *YourLibraryRequest) GetPseudoPlaylistConfig() *YourLibraryPseudoPlaylistConfig {
	if x != nil {
		return x.PseudoPlaylistConfig
	}
	return nil
}

func (x *YourLibraryRequest) GetUpdateThrottling() int32 {
	if x != nil {
		return x.UpdateThrottling
	}
	return 0
}

var File_spotify_your_library_your_library_request_proto protoreflect.FileDescriptor

const file_spotify_your_library_your_library_request_proto_rawDesc = "" +
	"\n" +
	"/spotify/your_library/your_library_request.proto\x12\x1aspotify.your_library.proto\x1a.spotify/your_library/your_library_config.proto\"/\n" +
	"\x14YourLibraryTagFilter\x12\x17\n" +
	"\atag_uri\x18\x01 \x01(\tR\x06tagUri\"\xcf\x01\n" +
	"\fCuratedItems\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\x12S\n" +
	"\x06filter\x18\x02 \x01(\x0e2;.spotify.your_library.proto.CuratedItems.CuratedItemsFilterR\x06filter\"T\n" +
	"\x12CuratedItemsFilter\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bGROUP_BY\x10\x01\x12\x10\n" +
	"\fONLY_CURATED\x10\x02\x12\x14\n" +
	"\x10ONLY_NOT_CURATED\x10\x03\"\xbd\a\n" +
	"\x18YourLibraryRequestHeader\x12-\n" +
	"\x12remaining_entities\x18\t \x01(\bR\x11remainingEntities\x12\x1f\n" +
	"\vtotal_count\x18\x12 \x01(\bR\n" +
	"totalCount\x12\x1f\n" +
	"\vlower_bound\x18\n" +
	" \x01(\tR\n" +
	"lowerBound\x12\x12\n" +
	"\x04skip\x18\v \x01(\x05R\x04skip\x12\x16\n" +
	"\x06length\x18\f \x01(\x05R\x06length\x12\x1f\n" +
	"\vtext_filter\x18\r \x01(\tR\n" +
	"textFilter\x12H\n" +
	"\afilters\x18\x0e \x01(\v2..spotify.your_library.proto.YourLibraryFiltersR\afilters\x12O\n" +
	"\n" +
	"sort_order\x18\x0f \x01(\v20.spotify.your_library.proto.YourLibrarySortOrderR\tsortOrder\x12#\n" +
	"\rall_playlists\x18\x11 \x01(\bR\fallPlaylists\x12!\n" +
	"\ffill_folders\x18\" \x03(\x03R\vfillFolders\x122\n" +
	"\x15separate_pinned_items\x18\x16 \x01(\bR\x13separatePinnedItems\x12<\n" +
	"\x1bnum_link_types_in_playlists\x18\x19 \x01(\bR\x17numLinkTypesInPlaylists\x12%\n" +
	"\x0eignore_pinning\x18\x1a \x01(\bR\rignorePinning\x12M\n" +
	"\rcurated_items\x18\x1d \x01(\v2(.spotify.your_library.proto.CuratedItemsR\fcuratedItems\x12%\n" +
	"\x0einclude_events\x18\x1e \x01(\bR\rincludeEvents\x12/\n" +
	"\x13include_prereleases\x18\x1f \x01(\bR\x12includePrereleases\x12'\n" +
	"\x0finclude_authors\x18! \x01(\bR\x0eincludeAuthors\x12\x1d\n" +
	"\tfolder_id\x18\x10 \x01(\x03H\x00R\bfolderId\x12Q\n" +
	"\n" +
	"tag_filter\x18\x18 \x01(\v20.spotify.your_library.proto.YourLibraryTagFilterH\x01R\ttagFilterB\x11\n" +
	"\x0fmaybe_folder_idB\x12\n" +
	"\x10maybe_tag_filter\"\x82\x02\n" +
	"\x12YourLibraryRequest\x12L\n" +
	"\x06header\x18\x01 \x01(\v24.spotify.your_library.proto.YourLibraryRequestHeaderR\x06header\x12q\n" +
	"\x16pseudo_playlist_config\x18\x04 \x01(\v2;.spotify.your_library.proto.YourLibraryPseudoPlaylistConfigR\x14pseudoPlaylistConfig\x12+\n" +
	"\x11update_throttling\x18\x05 \x01(\x05R\x10updateThrottlingB\xff\x01\n" +
	"\x1ecom.spotify.your_library.protoB\x17YourLibraryRequestProtoH\x01P\x01Z<github.com/mcMineyC/spotcontrol/proto/spotify/your_library\xa2\x02\x03SYP\xaa\x02\x19Spotify.YourLibrary.Proto\xca\x02\x19Spotify\\YourLibrary\\Proto\xe2\x02%Spotify\\YourLibrary\\Proto\\GPBMetadata\xea\x02\x1bSpotify::YourLibrary::Protob\x06proto3"

var (
	file_spotify_your_library_your_library_request_proto_rawDescOnce sync.Once
	file_spotify_your_library_your_library_request_proto_rawDescData []byte
)

func file_spotify_your_library_your_library_request_proto_rawDescGZIP() []byte {
	file_spotify_your_library_your_library_request_proto_rawDescOnce.Do(func() {
		file_spotify_your_library_your_library_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_request_proto_rawDesc), len(file_spotify_your_library_your_library_request_proto_rawDesc)))
	})
	return file_spotify_your_library_your_library_request_proto_rawDescData
}

var file_spotify_your_library_your_library_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spotify_your_library_your_library_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spotify_your_library_your_library_request_proto_goTypes = []any{
	(CuratedItems_CuratedItemsFilter)(0),    // 0: spotify.your_library.proto.CuratedItems.CuratedItemsFilter
	(*YourLibraryTagFilter)(nil),            // 1: spotify.your_library.proto.YourLibraryTagFilter
	(*CuratedItems)(nil),                    // 2: spotify.your_library.proto.CuratedItems
	(*YourLibraryRequestHeader)(nil),        // 3: spotify.your_library.proto.YourLibraryRequestHeader
	(*YourLibraryRequest)(nil),              // 4: spotify.your_library.proto.YourLibraryRequest
	(*YourLibraryFilters)(nil),              // 5: spotify.your_library.proto.YourLibraryFilters
	(*YourLibrarySortOrder)(nil),            // 6: spotify.your_library.proto.YourLibrarySortOrder
	(*YourLibraryPseudoPlaylistConfig)(nil), // 7: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig
}
var file_spotify_your_library_your_library_request_proto_depIdxs = []int32{
	0, // 0: spotify.your_library.proto.CuratedItems.filter:type_name -> spotify.your_library.proto.CuratedItems.CuratedItemsFilter
	5, // 1: spotify.your_library.proto.YourLibraryRequestHeader.filters:type_name -> spotify.your_library.proto.YourLibraryFilters
	6, // 2: spotify.your_library.proto.YourLibraryRequestHeader.sort_order:type_name -> spotify.your_library.proto.YourLibrarySortOrder
	2, // 3: spotify.your_library.proto.YourLibraryRequestHeader.curated_items:type_name -> spotify.your_library.proto.CuratedItems
	1, // 4: spotify.your_library.proto.YourLibraryRequestHeader.tag_filter:type_name -> spotify.your_library.proto.YourLibraryTagFilter
	3, // 5: spotify.your_library.proto.YourLibraryRequest.header:type_name -> spotify.your_library.proto.YourLibraryRequestHeader
	7, // 6: spotify.your_library.proto.YourLibraryRequest.pseudo_playlist_config:type_name -> spotify.your_library.proto.YourLibraryPseudoPlaylistConfig
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_spotify_your_library_your_library_request_proto_init() }
func file_spotify_your_library_your_library_request_proto_init() {
	if File_spotify_your_library_your_library_request_proto != nil {
		return
	}
	file_spotify_your_library_your_library_config_proto_init()
	file_spotify_your_library_your_library_request_proto_msgTypes[2].OneofWrappers = []any{
		(*YourLibraryRequestHeader_FolderId)(nil),
		(*YourLibraryRequestHeader_TagFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_request_proto_rawDesc), len(file_spotify_your_library_your_library_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_your_library_your_library_request_proto_goTypes,
		DependencyIndexes: file_spotify_your_library_your_library_request_proto_depIdxs,
		EnumInfos:         file_spotify_your_library_your_library_request_proto_enumTypes,
		MessageInfos:      file_spotify_your_library_your_library_request_proto_msgTypes,
	}.Build()
	File_spotify_your_library_your_library_request_proto = out.File
	file_spotify_your_library_your_library_request_proto_goTypes = nil
	file_spotify_your_library_your_library_request_proto_depIdxs = nil
}
