// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/your_library/your_library_config.proto

package your_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YourLibraryFilters_Filter int32

const (
	YourLibraryFilters_ALBUM       YourLibraryFilters_Filter = 0
	YourLibraryFilters_ARTIST      YourLibraryFilters_Filter = 1
	YourLibraryFilters_PLAYLIST    YourLibraryFilters_Filter = 2
	YourLibraryFilters_SHOW        YourLibraryFilters_Filter = 3
	YourLibraryFilters_BOOK        YourLibraryFilters_Filter = 4
	YourLibraryFilters_EVENT       YourLibraryFilters_Filter = 5
	YourLibraryFilters_AUTHOR      YourLibraryFilters_Filter = 7
	YourLibraryFilters_DOWNLOADED  YourLibraryFilters_Filter = 100
	YourLibraryFilters_WRITABLE    YourLibraryFilters_Filter = 101
	YourLibraryFilters_BY_YOU      YourLibraryFilters_Filter = 102
	YourLibraryFilters_BY_SPOTIFY  YourLibraryFilters_Filter = 103
	YourLibraryFilters_UNPLAYED    YourLibraryFilters_Filter = 104
	YourLibraryFilters_IN_PROGRESS YourLibraryFilters_Filter = 105
	YourLibraryFilters_FINISHED    YourLibraryFilters_Filter = 106
)

// Enum value maps for YourLibraryFilters_Filter.
var (
	YourLibraryFilters_Filter_name = map[int32]string{
		0:   "ALBUM",
		1:   "ARTIST",
		2:   "PLAYLIST",
		3:   "SHOW",
		4:   "BOOK",
		5:   "EVENT",
		7:   "AUTHOR",
		100: "DOWNLOADED",
		101: "WRITABLE",
		102: "BY_YOU",
		103: "BY_SPOTIFY",
		104: "UNPLAYED",
		105: "IN_PROGRESS",
		106: "FINISHED",
	}
	YourLibraryFilters_Filter_value = map[string]int32{
		"ALBUM":       0,
		"ARTIST":      1,
		"PLAYLIST":    2,
		"SHOW":        3,
		"BOOK":        4,
		"EVENT":       5,
		"AUTHOR":      7,
		"DOWNLOADED":  100,
		"WRITABLE":    101,
		"BY_YOU":      102,
		"BY_SPOTIFY":  103,
		"UNPLAYED":    104,
		"IN_PROGRESS": 105,
		"FINISHED":    106,
	}
)

func (x YourLibraryFilters_Filter) Enum() *YourLibraryFilters_Filter {
	p := new(YourLibraryFilters_Filter)
	*p = x
	return p
}

func (x YourLibraryFilters_Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryFilters_Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_your_library_your_library_config_proto_enumTypes[0].Descriptor()
}

func (YourLibraryFilters_Filter) Type() protoreflect.EnumType {
	return &file_spotify_your_library_your_library_config_proto_enumTypes[0]
}

func (x YourLibraryFilters_Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryFilters_Filter.Descriptor instead.
func (YourLibraryFilters_Filter) EnumDescriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{2, 0}
}

type YourLibrarySortOrder_SortOrder int32

const (
	YourLibrarySortOrder_NAME                     YourLibrarySortOrder_SortOrder = 0
	YourLibrarySortOrder_RECENTLY_ADDED           YourLibrarySortOrder_SortOrder = 1
	YourLibrarySortOrder_CREATOR                  YourLibrarySortOrder_SortOrder = 2
	YourLibrarySortOrder_CUSTOM                   YourLibrarySortOrder_SortOrder = 4
	YourLibrarySortOrder_RECENTLY_UPDATED         YourLibrarySortOrder_SortOrder = 5
	YourLibrarySortOrder_RECENTLY_PLAYED_OR_ADDED YourLibrarySortOrder_SortOrder = 6
	YourLibrarySortOrder_RELEVANCE                YourLibrarySortOrder_SortOrder = 7
	YourLibrarySortOrder_EVENT_START_TIME         YourLibrarySortOrder_SortOrder = 8
	YourLibrarySortOrder_RELEASE_DATE             YourLibrarySortOrder_SortOrder = 9
)

// Enum value maps for YourLibrarySortOrder_SortOrder.
var (
	YourLibrarySortOrder_SortOrder_name = map[int32]string{
		0: "NAME",
		1: "RECENTLY_ADDED",
		2: "CREATOR",
		4: "CUSTOM",
		5: "RECENTLY_UPDATED",
		6: "RECENTLY_PLAYED_OR_ADDED",
		7: "RELEVANCE",
		8: "EVENT_START_TIME",
		9: "RELEASE_DATE",
	}
	YourLibrarySortOrder_SortOrder_value = map[string]int32{
		"NAME":                     0,
		"RECENTLY_ADDED":           1,
		"CREATOR":                  2,
		"CUSTOM":                   4,
		"RECENTLY_UPDATED":         5,
		"RECENTLY_PLAYED_OR_ADDED": 6,
		"RELEVANCE":                7,
		"EVENT_START_TIME":         8,
		"RELEASE_DATE":             9,
	}
)

func (x YourLibrarySortOrder_SortOrder) Enum() *YourLibrarySortOrder_SortOrder {
	p := new(YourLibrarySortOrder_SortOrder)
	*p = x
	return p
}

func (x YourLibrarySortOrder_SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibrarySortOrder_SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_spotify_your_library_your_library_config_proto_enumTypes[1].Descriptor()
}

func (YourLibrarySortOrder_SortOrder) Type() protoreflect.EnumType {
	return &file_spotify_your_library_your_library_config_proto_enumTypes[1]
}

func (x YourLibrarySortOrder_SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibrarySortOrder_SortOrder.Descriptor instead.
func (YourLibrarySortOrder_SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{3, 0}
}

type YourLibraryLabelAndImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	IncludeEmpty  bool                   `protobuf:"varint,3,opt,name=include_empty,json=includeEmpty,proto3" json:"include_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryLabelAndImage) Reset() {
	*x = YourLibraryLabelAndImage{}
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryLabelAndImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryLabelAndImage) ProtoMessage() {}

func (x *YourLibraryLabelAndImage) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryLabelAndImage.ProtoReflect.Descriptor instead.
func (*YourLibraryLabelAndImage) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{0}
}

func (x *YourLibraryLabelAndImage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *YourLibraryLabelAndImage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *YourLibraryLabelAndImage) GetIncludeEmpty() bool {
	if x != nil {
		return x.IncludeEmpty
	}
	return false
}

type YourLibraryPseudoPlaylistConfig struct {
	state                       protoimpl.MessageState    `protogen:"open.v1"`
	LikedSongs                  *YourLibraryLabelAndImage `protobuf:"bytes,1,opt,name=liked_songs,json=likedSongs,proto3" json:"liked_songs,omitempty"`
	YourEpisodes                *YourLibraryLabelAndImage `protobuf:"bytes,2,opt,name=your_episodes,json=yourEpisodes,proto3" json:"your_episodes,omitempty"`
	NewEpisodes                 *YourLibraryLabelAndImage `protobuf:"bytes,3,opt,name=new_episodes,json=newEpisodes,proto3" json:"new_episodes,omitempty"`
	LocalFiles                  *YourLibraryLabelAndImage `protobuf:"bytes,4,opt,name=local_files,json=localFiles,proto3" json:"local_files,omitempty"`
	CachedFiles                 *YourLibraryLabelAndImage `protobuf:"bytes,5,opt,name=cached_files,json=cachedFiles,proto3" json:"cached_files,omitempty"`
	YourHighlights              bool                      `protobuf:"varint,6,opt,name=your_highlights,json=yourHighlights,proto3" json:"your_highlights,omitempty"`
	AllAvailableConfigsProvided bool                      `protobuf:"varint,99,opt,name=all_available_configs_provided,json=allAvailableConfigsProvided,proto3" json:"all_available_configs_provided,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *YourLibraryPseudoPlaylistConfig) Reset() {
	*x = YourLibraryPseudoPlaylistConfig{}
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryPseudoPlaylistConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryPseudoPlaylistConfig) ProtoMessage() {}

func (x *YourLibraryPseudoPlaylistConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryPseudoPlaylistConfig.ProtoReflect.Descriptor instead.
func (*YourLibraryPseudoPlaylistConfig) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{1}
}

func (x *YourLibraryPseudoPlaylistConfig) GetLikedSongs() *YourLibraryLabelAndImage {
	if x != nil {
		return x.LikedSongs
	}
	return nil
}

func (x *YourLibraryPseudoPlaylistConfig) GetYourEpisodes() *YourLibraryLabelAndImage {
	if x != nil {
		return x.YourEpisodes
	}
	return nil
}

func (x *YourLibraryPseudoPlaylistConfig) GetNewEpisodes() *YourLibraryLabelAndImage {
	if x != nil {
		return x.NewEpisodes
	}
	return nil
}

func (x *YourLibraryPseudoPlaylistConfig) GetLocalFiles() *YourLibraryLabelAndImage {
	if x != nil {
		return x.LocalFiles
	}
	return nil
}

func (x *YourLibraryPseudoPlaylistConfig) GetCachedFiles() *YourLibraryLabelAndImage {
	if x != nil {
		return x.CachedFiles
	}
	return nil
}

func (x *YourLibraryPseudoPlaylistConfig) GetYourHighlights() bool {
	if x != nil {
		return x.YourHighlights
	}
	return false
}

func (x *YourLibraryPseudoPlaylistConfig) GetAllAvailableConfigsProvided() bool {
	if x != nil {
		return x.AllAvailableConfigsProvided
	}
	return false
}

type YourLibraryFilters struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Filter        []YourLibraryFilters_Filter `protobuf:"varint,1,rep,packed,name=filter,proto3,enum=spotify.your_library.proto.YourLibraryFilters_Filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryFilters) Reset() {
	*x = YourLibraryFilters{}
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryFilters) ProtoMessage() {}

func (x *YourLibraryFilters) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryFilters.ProtoReflect.Descriptor instead.
func (*YourLibraryFilters) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{2}
}

func (x *YourLibraryFilters) GetFilter() []YourLibraryFilters_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type YourLibrarySortOrder struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SortOrder     YourLibrarySortOrder_SortOrder `protobuf:"varint,1,opt,name=sort_order,json=sortOrder,proto3,enum=spotify.your_library.proto.YourLibrarySortOrder_SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibrarySortOrder) Reset() {
	*x = YourLibrarySortOrder{}
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibrarySortOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibrarySortOrder) ProtoMessage() {}

func (x *YourLibrarySortOrder) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibrarySortOrder.ProtoReflect.Descriptor instead.
func (*YourLibrarySortOrder) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_config_proto_rawDescGZIP(), []int{3}
}

func (x *YourLibrarySortOrder) GetSortOrder() YourLibrarySortOrder_SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return YourLibrarySortOrder_NAME
}

var File_spotify_your_library_your_library_config_proto protoreflect.FileDescriptor

const file_spotify_your_library_your_library_config_proto_rawDesc = "" +
	"\n" +
	".spotify/your_library/your_library_config.proto\x12\x1aspotify.your_library.proto\"k\n" +
	"\x18YourLibraryLabelAndImage\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\rinclude_empty\x18\x03 \x01(\bR\fincludeEmpty\"\xca\x04\n" +
	"\x1fYourLibraryPseudoPlaylistConfig\x12U\n" +
	"\vliked_songs\x18\x01 \x01(\v24.spotify.your_library.proto.YourLibraryLabelAndImageR\n" +
	"likedSongs\x12Y\n" +
	"\ryour_episodes\x18\x02 \x01(\v24.spotify.your_library.proto.YourLibraryLabelAndImageR\fyourEpisodes\x12W\n" +
	"\fnew_episodes\x18\x03 \x01(\v24.spotify.your_library.proto.YourLibraryLabelAndImageR\vnewEpisodes\x12U\n" +
	"\vlocal_files\x18\x04 \x01(\v24.spotify.your_library.proto.YourLibraryLabelAndImageR\n" +
	"localFiles\x12W\n" +
	"\fcached_files\x18\x05 \x01(\v24.spotify.your_library.proto.YourLibraryLabelAndImageR\vcachedFiles\x12'\n" +
	"\x0fyour_highlights\x18\x06 \x01(\bR\x0eyourHighlights\x12C\n" +
	"\x1eall_available_configs_provided\x18c \x01(\bR\x1ballAvailableConfigsProvided\"\xa5\x02\n" +
	"\x12YourLibraryFilters\x12M\n" +
	"\x06filter\x18\x01 \x03(\x0e25.spotify.your_library.proto.YourLibraryFilters.FilterR\x06filter\"\xbf\x01\n" +
	"\x06Filter\x12\t\n" +
	"\x05ALBUM\x10\x00\x12\n" +
	"\n" +
	"\x06ARTIST\x10\x01\x12\f\n" +
	"\bPLAYLIST\x10\x02\x12\b\n" +
	"\x04SHOW\x10\x03\x12\b\n" +
	"\x04BOOK\x10\x04\x12\t\n" +
	"\x05EVENT\x10\x05\x12\n" +
	"\n" +
	"\x06AUTHOR\x10\a\x12\x0e\n" +
	"\n" +
	"DOWNLOADED\x10d\x12\f\n" +
	"\bWRITABLE\x10e\x12\n" +
	"\n" +
	"\x06BY_YOU\x10f\x12\x0e\n" +
	"\n" +
	"BY_SPOTIFY\x10g\x12\f\n" +
	"\bUNPLAYED\x10h\x12\x0f\n" +
	"\vIN_PROGRESS\x10i\x12\f\n" +
	"\bFINISHED\x10j\"\xa1\x02\n" +
	"\x14YourLibrarySortOrder\x12Y\n" +
	"\n" +
	"sort_order\x18\x01 \x01(\x0e2:.spotify.your_library.proto.YourLibrarySortOrder.SortOrderR\tsortOrder\"\xad\x01\n" +
	"\tSortOrder\x12\b\n" +
	"\x04NAME\x10\x00\x12\x12\n" +
	"\x0eRECENTLY_ADDED\x10\x01\x12\v\n" +
	"\aCREATOR\x10\x02\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x04\x12\x14\n" +
	"\x10RECENTLY_UPDATED\x10\x05\x12\x1c\n" +
	"\x18RECENTLY_PLAYED_OR_ADDED\x10\x06\x12\r\n" +
	"\tRELEVANCE\x10\a\x12\x14\n" +
	"\x10EVENT_START_TIME\x10\b\x12\x10\n" +
	"\fRELEASE_DATE\x10\tB\xfc\x01\n" +
	"\x1ecom.spotify.your_library.protoB\x16YourLibraryConfigProtoP\x01Z<github.com/mcMineyC/spotcontrol/proto/spotify/your_library\xa2\x02\x03SYP\xaa\x02\x19Spotify.YourLibrary.Proto\xca\x02\x19Spotify\\YourLibrary\\Proto\xe2\x02%Spotify\\YourLibrary\\Proto\\GPBMetadata\xea\x02\x1bSpotify::YourLibrary::Protob\x06proto3"

var (
	file_spotify_your_library_your_library_config_proto_rawDescOnce sync.Once
	file_spotify_your_library_your_library_config_proto_rawDescData []byte
)

func file_spotify_your_library_your_library_config_proto_rawDescGZIP() []byte {
	file_spotify_your_library_your_library_config_proto_rawDescOnce.Do(func() {
		file_spotify_your_library_your_library_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_config_proto_rawDesc), len(file_spotify_your_library_your_library_config_proto_rawDesc)))
	})
	return file_spotify_your_library_your_library_config_proto_rawDescData
}

var file_spotify_your_library_your_library_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spotify_your_library_your_library_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spotify_your_library_your_library_config_proto_goTypes = []any{
	(YourLibraryFilters_Filter)(0),          // 0: spotify.your_library.proto.YourLibraryFilters.Filter
	(YourLibrarySortOrder_SortOrder)(0),     // 1: spotify.your_library.proto.YourLibrarySortOrder.SortOrder
	(*YourLibraryLabelAndImage)(nil),        // 2: spotify.your_library.proto.YourLibraryLabelAndImage
	(*YourLibraryPseudoPlaylistConfig)(nil), // 3: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig
	(*YourLibraryFilters)(nil),              // 4: spotify.your_library.proto.YourLibraryFilters
	(*YourLibrarySortOrder)(nil),            // 5: spotify.your_library.proto.YourLibrarySortOrder
}
var file_spotify_your_library_your_library_config_proto_depIdxs = []int32{
	2, // 0: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig.liked_songs:type_name -> spotify.your_library.proto.YourLibraryLabelAndImage
	2, // 1: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig.your_episodes:type_name -> spotify.your_library.proto.YourLibraryLabelAndImage
	2, // 2: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig.new_episodes:type_name -> spotify.your_library.proto.YourLibraryLabelAndImage
	2, // 3: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig.local_files:type_name -> spotify.your_library.proto.YourLibraryLabelAndImage
	2, // 4: spotify.your_library.proto.YourLibraryPseudoPlaylistConfig.cached_files:type_name -> spotify.your_library.proto.YourLibraryLabelAndImage
	0, // 5: spotify.your_library.proto.YourLibraryFilters.filter:type_name -> spotify.your_library.proto.YourLibraryFilters.Filter
	1, // 6: spotify.your_library.proto.YourLibrarySortOrder.sort_order:type_name -> spotify.your_library.proto.YourLibrarySortOrder.SortOrder
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_spotify_your_library_your_library_config_proto_init() }
func file_spotify_your_library_your_library_config_proto_init() {
	if File_spotify_your_library_your_library_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_config_proto_rawDesc), len(file_spotify_your_library_your_library_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_your_library_your_library_config_proto_goTypes,
		DependencyIndexes: file_spotify_your_library_your_library_config_proto_depIdxs,
		EnumInfos:         file_spotify_your_library_your_library_config_proto_enumTypes,
		MessageInfos:      file_spotify_your_library_your_library_config_proto_msgTypes,
	}.Build()
	File_spotify_your_library_your_library_config_proto = out.File
	file_spotify_your_library_your_library_config_proto_goTypes = nil
	file_spotify_your_library_your_library_config_proto_depIdxs = nil
}
