// Extracted from: Spotify 1.2.52.442 (windows)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: spotify/your_library/your_library_response.proto

package your_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YourLibraryTagPlaylist struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri                 string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUri            string                 `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	OfflineAvailability Offline_Availability   `protobuf:"varint,5,opt,name=offline_availability,json=offlineAvailability,proto3,enum=spotify.your_library.proto.Offline_Availability" json:"offline_availability,omitempty"`
	IsCurated           bool                   `protobuf:"varint,6,opt,name=is_curated,json=isCurated,proto3" json:"is_curated,omitempty"`
	IsLoading           bool                   `protobuf:"varint,7,opt,name=is_loading,json=isLoading,proto3" json:"is_loading,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *YourLibraryTagPlaylist) Reset() {
	*x = YourLibraryTagPlaylist{}
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryTagPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryTagPlaylist) ProtoMessage() {}

func (x *YourLibraryTagPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryTagPlaylist.ProtoReflect.Descriptor instead.
func (*YourLibraryTagPlaylist) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_response_proto_rawDescGZIP(), []int{0}
}

func (x *YourLibraryTagPlaylist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YourLibraryTagPlaylist) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *YourLibraryTagPlaylist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *YourLibraryTagPlaylist) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *YourLibraryTagPlaylist) GetOfflineAvailability() Offline_Availability {
	if x != nil {
		return x.OfflineAvailability
	}
	return Offline_UNKNOWN
}

func (x *YourLibraryTagPlaylist) GetIsCurated() bool {
	if x != nil {
		return x.IsCurated
	}
	return false
}

func (x *YourLibraryTagPlaylist) GetIsLoading() bool {
	if x != nil {
		return x.IsLoading
	}
	return false
}

type YourLibraryTagInfo struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	TagName         string                  `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	IsAdded         bool                    `protobuf:"varint,5,opt,name=is_added,json=isAdded,proto3" json:"is_added,omitempty"`
	TagPlaylistInfo *YourLibraryTagPlaylist `protobuf:"bytes,7,opt,name=tag_playlist_info,json=tagPlaylistInfo,proto3" json:"tag_playlist_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *YourLibraryTagInfo) Reset() {
	*x = YourLibraryTagInfo{}
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryTagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryTagInfo) ProtoMessage() {}

func (x *YourLibraryTagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryTagInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryTagInfo) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_response_proto_rawDescGZIP(), []int{1}
}

func (x *YourLibraryTagInfo) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *YourLibraryTagInfo) GetIsAdded() bool {
	if x != nil {
		return x.IsAdded
	}
	return false
}

func (x *YourLibraryTagInfo) GetTagPlaylistInfo() *YourLibraryTagPlaylist {
	if x != nil {
		return x.TagPlaylistInfo
	}
	return nil
}

type YourLibraryResponseHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RemainingEntities  int32                  `protobuf:"varint,9,opt,name=remaining_entities,json=remainingEntities,proto3" json:"remaining_entities,omitempty"`
	TotalCount         int32                  `protobuf:"varint,17,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PinCount           int32                  `protobuf:"varint,18,opt,name=pin_count,json=pinCount,proto3" json:"pin_count,omitempty"`
	MaximumPinnedItems int32                  `protobuf:"varint,19,opt,name=maximum_pinned_items,json=maximumPinnedItems,proto3" json:"maximum_pinned_items,omitempty"`
	IsLoading          bool                   `protobuf:"varint,12,opt,name=is_loading,json=isLoading,proto3" json:"is_loading,omitempty"`
	FolderName         string                 `protobuf:"bytes,15,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	ParentFolderUri    string                 `protobuf:"bytes,20,opt,name=parent_folder_uri,json=parentFolderUri,proto3" json:"parent_folder_uri,omitempty"`
	AvailableFilters   *YourLibraryFilters    `protobuf:"bytes,16,opt,name=available_filters,json=availableFilters,proto3" json:"available_filters,omitempty"`
	TagInfo            *YourLibraryTagInfo    `protobuf:"bytes,21,opt,name=tag_info,json=tagInfo,proto3" json:"tag_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *YourLibraryResponseHeader) Reset() {
	*x = YourLibraryResponseHeader{}
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryResponseHeader) ProtoMessage() {}

func (x *YourLibraryResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryResponseHeader.ProtoReflect.Descriptor instead.
func (*YourLibraryResponseHeader) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_response_proto_rawDescGZIP(), []int{2}
}

func (x *YourLibraryResponseHeader) GetRemainingEntities() int32 {
	if x != nil {
		return x.RemainingEntities
	}
	return 0
}

func (x *YourLibraryResponseHeader) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *YourLibraryResponseHeader) GetPinCount() int32 {
	if x != nil {
		return x.PinCount
	}
	return 0
}

func (x *YourLibraryResponseHeader) GetMaximumPinnedItems() int32 {
	if x != nil {
		return x.MaximumPinnedItems
	}
	return 0
}

func (x *YourLibraryResponseHeader) GetIsLoading() bool {
	if x != nil {
		return x.IsLoading
	}
	return false
}

func (x *YourLibraryResponseHeader) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *YourLibraryResponseHeader) GetParentFolderUri() string {
	if x != nil {
		return x.ParentFolderUri
	}
	return ""
}

func (x *YourLibraryResponseHeader) GetAvailableFilters() *YourLibraryFilters {
	if x != nil {
		return x.AvailableFilters
	}
	return nil
}

func (x *YourLibraryResponseHeader) GetTagInfo() *YourLibraryTagInfo {
	if x != nil {
		return x.TagInfo
	}
	return nil
}

type YourLibraryResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Header        *YourLibraryResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Entity        []*YourLibraryDecoratedEntity `protobuf:"bytes,2,rep,name=entity,proto3" json:"entity,omitempty"`
	PinnedEntity  []*YourLibraryDecoratedEntity `protobuf:"bytes,3,rep,name=pinned_entity,json=pinnedEntity,proto3" json:"pinned_entity,omitempty"`
	StatusCode    int32                         `protobuf:"varint,98,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         string                        `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryResponse) Reset() {
	*x = YourLibraryResponse{}
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryResponse) ProtoMessage() {}

func (x *YourLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_your_library_your_library_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryResponse.ProtoReflect.Descriptor instead.
func (*YourLibraryResponse) Descriptor() ([]byte, []int) {
	return file_spotify_your_library_your_library_response_proto_rawDescGZIP(), []int{3}
}

func (x *YourLibraryResponse) GetHeader() *YourLibraryResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *YourLibraryResponse) GetEntity() []*YourLibraryDecoratedEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *YourLibraryResponse) GetPinnedEntity() []*YourLibraryDecoratedEntity {
	if x != nil {
		return x.PinnedEntity
	}
	return nil
}

func (x *YourLibraryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *YourLibraryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_spotify_your_library_your_library_response_proto protoreflect.FileDescriptor

const file_spotify_your_library_your_library_response_proto_rawDesc = "" +
	"\n" +
	"0spotify/your_library/your_library_response.proto\x12\x1aspotify.your_library.proto\x1a8spotify/your_library/your_library_decorated_entity.proto\x1a.spotify/your_library/your_library_config.proto\"\xa0\x02\n" +
	"\x16YourLibraryTagPlaylist\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_uri\x18\x04 \x01(\tR\bimageUri\x12c\n" +
	"\x14offline_availability\x18\x05 \x01(\x0e20.spotify.your_library.proto.Offline.AvailabilityR\x13offlineAvailability\x12\x1d\n" +
	"\n" +
	"is_curated\x18\x06 \x01(\bR\tisCurated\x12\x1d\n" +
	"\n" +
	"is_loading\x18\a \x01(\bR\tisLoading\"\xaa\x01\n" +
	"\x12YourLibraryTagInfo\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12\x19\n" +
	"\bis_added\x18\x05 \x01(\bR\aisAdded\x12^\n" +
	"\x11tag_playlist_info\x18\a \x01(\v22.spotify.your_library.proto.YourLibraryTagPlaylistR\x0ftagPlaylistInfo\"\xce\x03\n" +
	"\x19YourLibraryResponseHeader\x12-\n" +
	"\x12remaining_entities\x18\t \x01(\x05R\x11remainingEntities\x12\x1f\n" +
	"\vtotal_count\x18\x11 \x01(\x05R\n" +
	"totalCount\x12\x1b\n" +
	"\tpin_count\x18\x12 \x01(\x05R\bpinCount\x120\n" +
	"\x14maximum_pinned_items\x18\x13 \x01(\x05R\x12maximumPinnedItems\x12\x1d\n" +
	"\n" +
	"is_loading\x18\f \x01(\bR\tisLoading\x12\x1f\n" +
	"\vfolder_name\x18\x0f \x01(\tR\n" +
	"folderName\x12*\n" +
	"\x11parent_folder_uri\x18\x14 \x01(\tR\x0fparentFolderUri\x12[\n" +
	"\x11available_filters\x18\x10 \x01(\v2..spotify.your_library.proto.YourLibraryFiltersR\x10availableFilters\x12I\n" +
	"\btag_info\x18\x15 \x01(\v2..spotify.your_library.proto.YourLibraryTagInfoR\atagInfo\"\xc8\x02\n" +
	"\x13YourLibraryResponse\x12M\n" +
	"\x06header\x18\x01 \x01(\v25.spotify.your_library.proto.YourLibraryResponseHeaderR\x06header\x12N\n" +
	"\x06entity\x18\x02 \x03(\v26.spotify.your_library.proto.YourLibraryDecoratedEntityR\x06entity\x12[\n" +
	"\rpinned_entity\x18\x03 \x03(\v26.spotify.your_library.proto.YourLibraryDecoratedEntityR\fpinnedEntity\x12\x1f\n" +
	"\vstatus_code\x18b \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18c \x01(\tR\x05errorB\x80\x02\n" +
	"\x1ecom.spotify.your_library.protoB\x18YourLibraryResponseProtoH\x01P\x01Z<github.com/mcMineyC/spotcontrol/proto/spotify/your_library\xa2\x02\x03SYP\xaa\x02\x19Spotify.YourLibrary.Proto\xca\x02\x19Spotify\\YourLibrary\\Proto\xe2\x02%Spotify\\YourLibrary\\Proto\\GPBMetadata\xea\x02\x1bSpotify::YourLibrary::Protob\x06proto3"

var (
	file_spotify_your_library_your_library_response_proto_rawDescOnce sync.Once
	file_spotify_your_library_your_library_response_proto_rawDescData []byte
)

func file_spotify_your_library_your_library_response_proto_rawDescGZIP() []byte {
	file_spotify_your_library_your_library_response_proto_rawDescOnce.Do(func() {
		file_spotify_your_library_your_library_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_response_proto_rawDesc), len(file_spotify_your_library_your_library_response_proto_rawDesc)))
	})
	return file_spotify_your_library_your_library_response_proto_rawDescData
}

var file_spotify_your_library_your_library_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spotify_your_library_your_library_response_proto_goTypes = []any{
	(*YourLibraryTagPlaylist)(nil),     // 0: spotify.your_library.proto.YourLibraryTagPlaylist
	(*YourLibraryTagInfo)(nil),         // 1: spotify.your_library.proto.YourLibraryTagInfo
	(*YourLibraryResponseHeader)(nil),  // 2: spotify.your_library.proto.YourLibraryResponseHeader
	(*YourLibraryResponse)(nil),        // 3: spotify.your_library.proto.YourLibraryResponse
	(Offline_Availability)(0),          // 4: spotify.your_library.proto.Offline.Availability
	(*YourLibraryFilters)(nil),         // 5: spotify.your_library.proto.YourLibraryFilters
	(*YourLibraryDecoratedEntity)(nil), // 6: spotify.your_library.proto.YourLibraryDecoratedEntity
}
var file_spotify_your_library_your_library_response_proto_depIdxs = []int32{
	4, // 0: spotify.your_library.proto.YourLibraryTagPlaylist.offline_availability:type_name -> spotify.your_library.proto.Offline.Availability
	0, // 1: spotify.your_library.proto.YourLibraryTagInfo.tag_playlist_info:type_name -> spotify.your_library.proto.YourLibraryTagPlaylist
	5, // 2: spotify.your_library.proto.YourLibraryResponseHeader.available_filters:type_name -> spotify.your_library.proto.YourLibraryFilters
	1, // 3: spotify.your_library.proto.YourLibraryResponseHeader.tag_info:type_name -> spotify.your_library.proto.YourLibraryTagInfo
	2, // 4: spotify.your_library.proto.YourLibraryResponse.header:type_name -> spotify.your_library.proto.YourLibraryResponseHeader
	6, // 5: spotify.your_library.proto.YourLibraryResponse.entity:type_name -> spotify.your_library.proto.YourLibraryDecoratedEntity
	6, // 6: spotify.your_library.proto.YourLibraryResponse.pinned_entity:type_name -> spotify.your_library.proto.YourLibraryDecoratedEntity
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_spotify_your_library_your_library_response_proto_init() }
func file_spotify_your_library_your_library_response_proto_init() {
	if File_spotify_your_library_your_library_response_proto != nil {
		return
	}
	file_spotify_your_library_your_library_decorated_entity_proto_init()
	file_spotify_your_library_your_library_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_your_library_your_library_response_proto_rawDesc), len(file_spotify_your_library_your_library_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_your_library_your_library_response_proto_goTypes,
		DependencyIndexes: file_spotify_your_library_your_library_response_proto_depIdxs,
		MessageInfos:      file_spotify_your_library_your_library_response_proto_msgTypes,
	}.Build()
	File_spotify_your_library_your_library_response_proto = out.File
	file_spotify_your_library_your_library_response_proto_goTypes = nil
	file_spotify_your_library_your_library_response_proto_depIdxs = nil
}
